"""Reviewed non-secret hold codes shared by job projections and activities."""

APPLICATION_HOLD_CODES = frozenset({
    'CURRENT_AUTHORITY_UNAVAILABLE', 'DATASET_EFFECT_REQUIRES_RECONCILIATION',
    'SOURCE_POWER_REQUIRES_RECONCILIATION',
    'SOURCE_RESTART_OR_OTHER_WRITER_EXCLUSION_REQUIRED',
    'ISOLATED_REHEARSAL_OWNER_UNAVAILABLE', 'FINAL_CONSISTENCY_OWNER_UNAVAILABLE',
    'TRAFFIC_AND_TARGET_ACTIVATION_OWNER_UNAVAILABLE',
    'CURRENT_TARGET_WRITE_STATE_REQUIRED', 'POSTWRITE_RECOVERY_OWNER_UNAVAILABLE',
    'PREWRITE_TARGET_EXCLUSION_REQUIRED', 'PRIVATE_MIGRATION_INPUTS_UNAVAILABLE',
    'GUEST_PER_COMMAND_AUTHORITY_UNAVAILABLE', 'SCOPED_PLANNING_CREDENTIAL_OWNER_UNAVAILABLE',
    'NATIVE_STAGE_OWNER_UNAVAILABLE',
    'NATIVE_ORIGINAL_RECOVERY_OWNER_UNAVAILABLE', 'FINAL_APPLICATION_ACCEPTANCE_UNAVAILABLE',
})
