from catalogue import ROOT,csvwrite
import json
out=ROOT/'03_Implementation/runbooks'
books=[
('RB-00','Release_Preflight','Release, scope and execution preflight','Change owner','Approved engineering release; actual site resources; no native operation begins until preflight is accepted.','RA §§20–25; WD §§9–10; IT §§1–2',[
('Identify the delivery','Confirm the service, site, tenant/data scope, environment and work package.','Scope and exclusions match the change request.','Stop if the actual target or owner differs.','Scope record and target inventory.'),
('Freeze the engineering input','Resolve the HLD/LLD revision, drawings, schedules, exact tuple, approved configuration artifacts and hashes.','One controlled build baseline is identified.','Do not substitute moving latest versions or missing configuration.','Design/artifact manifest.'),
('Confirm authority and safety','Name executors, reviewer, stop/escalation authority, change window and allowed physical or intrusive-test scope.','Required permissions and site safety releases apply to this action.','No authorization or unsafe conditions: do not start.','Actual change/test decision and safety scope.'),
('Prove access and recovery','Verify approved management path, protected credential custody, independent recovery access and data-safe recovery method.','Recovery is usable for the failure this change can cause.','Do not change the only working access path without the accepted recovery arrangement.','Access and recovery preflight result.'),
('Review competing work','Check current owners, native tasks, locks, incidents and relevant resource/policy revisions.','Single authoritative writer; no unresolved late task or stale approval.','Pause and reconcile conflicts rather than overriding them.','Task/ownership review and current-state snapshot.'),
('Issue ready-to-execute record','Reviewer accepts the bounded MOP; record conditions and expiry.','Execution may proceed only inside the issued scope.','A kit checklist completion is not the authority decision.','Signed or attributable preflight disposition.')]),
('RB-01','P0_P1_Foundation','P0–P1 bootstrap and physical foundation','Foundation deployment lead','RB-00 accepted; actual equipment, facility interfaces, addresses, routing design, configuration method and custody resolved.','RA §§3–6,21; PROV §2; ET §§2–3',[
('Verify staged inventory','Reconcile received hardware/software/entitlements against the accepted BOM and trusted source.','Components and firmware/driver tuple are accounted for.','Quarantine mismatched or unverified items; retain custody evidence.','Inventory and compatibility receipt.'),
('Accept physical installation','Qualified personnel complete approved manufacturer/facility installation and record links, racks, power and failure groups.','Physical topology matches the released design.','Do not improvise electrical, lifting or restricted facility procedures.','Facility installation and port/cable receipts.'),
('Establish bootstrap trust','Use the supported restricted console/OOB process and controlled temporary identity; provide accepted minimum time/name/trust.','Privileged access is restricted and recoverable without tenant routing.','Do not enable broad workload management reachability to finish bootstrap.','Bootstrap access, dependency and temporary-grant record.'),
('Commission transport','Apply the accepted native configuration through the authoritative tool; verify neighbors, allowed routes, MTU and attachment membership.','Observed underlay/fabric matches the selected design.','Unexpected route import or bypass: stop, isolate affected scope and follow supported recovery.','Native configuration, routing and path observations.'),
('Verify the failure boundary','Run only approved link/management fault observations with restoration procedures.','Required access and enforcement survive as specified; interruption measured.','No unapproved fault injection; do not treat denied traffic as proof of availability.','Fault scope, observations and restoration receipt.'),
('Release G1 scope','Handover actual configuration, inventory, recovery copy, telemetry, capacity and limitations.','Dependent platform work consumes accepted foundation capacity.','Open mandatory foundation issue blocks affected consumption.','G1 decision and P1 handoff.')]),
('RB-02','Nutanix_P2','Nutanix native platform commissioning','Nutanix platform owner','RB-00 and applicable G1; selected AOS/AHV/Prism/Flow tuple, hardware, support, licenses and native installer procedure.','RA §16,22; VND §3; VC §2; K05',[
('Confirm native support','Resolve cluster, manager, Flow, provider/API and hardware compatibility and enabled feature scope.','Every needed operation has support evidence or an accepted alternative.','A v2 resource name or provider availability is not full support.','Tuple/operation-coverage record.'),
('Install under native ownership','Execute the approved vendor installation/lifecycle artifact with the protected management path.','Native cluster and control services are healthy at the recorded versions.','Use supported recovery on failure; never create a competing configuration owner.','Installer and native task receipts.'),
('Establish eligible pools','Configure approved host/zone/co-residency eligibility, storage/controller membership, templates and protection integration.','Placement and restart constraints cover actual shared dependencies.','Do not treat separate guest networks as physical isolation.','Placement/storage/management as-built.'),
('Commission virtual network capability','Prepare platform transport and isolated external handoff capacity; verify supported gateway/no-NAT/NAT choice and policy ownership.','Independent domain routing and baseline controls precede endpoints.','Shared connected external paths remain ineligible until isolation is proven.','Native handoff, route and policy observations.'),
('Create authorized disposable fixture','Under restricted test permission, realize the WD logical roles with site allocations and current mandatory policy.','Fixture ownership is stable; partial resources remain denied.','Do not use documentation addresses as actual allocations or introduce production data.','Fixture inventory and build receipts.'),
('Qualify and hand over','Observe relevant W14/CT outcomes, failure and restore; record actual resource create/update/adopt/delete handling.','Accepted capability scope and limitations available for G2.','Unrun or failed mandatory observation remains open.','Qualification report, native IDs and G2 scope decision.')]),
('RB-03','VMware_NSX_P2','VMware/NSX native platform commissioning','VMware/NSX platform owners','RB-00 and G1; actual ESXi/vCenter/NSX/provider/hardware/entitlement tuple, gateway modes and supported installation artifacts.','RA §17,22; VND §4; VC §3; KIT-TN-01',[
('Confirm routing-mode compatibility','Validate exact Tier-1/upstream context, parent Tier-0/VRF and HA mode against installed-release documentation and KIT-TN-01.','Selected modes and service functions are supported together.','Do not change a live parent mode merely to satisfy this checklist; require a separate impact-reviewed change.','Gateway compatibility decision.'),
('Commission compute/storage management','Execute approved native vCenter/ESXi and storage installation, eligible pools, image/boot and management configuration.','Actual placements and data dependencies match the LLD.','Unsupported tuple or hidden shared management boundary blocks service acceptance.','Platform installation and pool as-built.'),
('Commission NSX transport and edge','Establish approved managers, transport nodes/zones, Edge capacity, uplinks and isolated upstream contexts.','Actual distributed and centralized routing roles are identifiable.','No common unrestricted native route table substitutes for the security boundary.','Transport/gateway/Edge configuration and path record.'),
('Protect mandatory endpoint and edge policy','Apply provider-owned groups, policy hierarchy and separately authorized ZIP relationships before workload connection.','Same-host and cross-host controls cannot be widened by tenant mutation.','Unexpected permissive default or override path keeps resources isolated.','Effective policy and role observations.'),
('Run restricted fixture and faults','Build the accepted disposable domains/VMs/disks; observe native route propagation, return context, HA/restart and protection.','Observed outcomes support the offered service and actual failure scope.','No unsupported HA or live-migration promise; stop unsafe fault execution.','Qualified test observations and recovery receipts.'),
('Release scoped capability','Record vSphere/NSX ownership, provider lifecycle coverage, actual limits, limitations and evidence.','G2 considers a concrete service/tuple rather than product names.','Missing exact evidence prevents qualification.','As-built/coverage and qualification decision.')]),
('RB-04','OpenStack_P2','OpenStack native platform commissioning','OpenStack distribution/service owners','RB-00 and G1; exact distribution/services/backend, API policy, hardware, installer and provider tuple resolved.','RA §18,22; VND §5; VC §4; K06–K08',[
('Resolve selected services and backend','Record Keystone, Nova/Placement, Neutron backend, Glance/Cinder and all offered data/trust/protection services.','No unsupported feature is inferred from generic OpenStack naming.','Distribution or backend uncertainty blocks affected design.','Versioned service/extension matrix.'),
('Install using supported lifecycle tooling','Deploy the approved controllers/databases/messaging, compute and backend infrastructure under native ownership.','Control/data dependencies and quorum are observed.','Do not manage Neutron-owned OVN objects through a competing raw writer.','Installer/native health and ownership receipts.'),
('Enforce placement and data boundaries','Configure actual scheduler/aggregate/trait eligibility, volume backend classes and image/key controls.','Tenant, zone and restart/restore constraints are effective.','Labels without enforced placement do not satisfy isolation.','Scheduling decisions and data-attachment observations.'),
('Protect network mutation authority','Implement provider ownership of base mandatory groups, port security, address pairs, routers and external attachments through the supported role model.','Tenant permissions cannot attach an additive allow or disable required protection.','Unbounded tenant editing is not base-service qualification.','API role tests and effective policy review.'),
('Verify domain and service paths','Build restricted distinct domains and handoffs; observe distributed routes, gateways, default egress normalization, metadata/boot services and replies.','Approved services work; connected/provider/floating-address shortcuts do not bypass controls.','Avoid blanket deny that hides broken initialization or IPv6 operation.','Positive/negative path and native configuration evidence.'),
('Qualify lifecycle and recovery','Observe supported create/update/adopt/delete, task cleanup, gateway/host failure, Cinder isolation and restore.','Concrete tuple/service accepted or explicitly limited at G2.','Unknown residual ports/routes/grants remain defects.','As-built, limitations, evidence and decision.')]),
('RB-05','P3_Shared_Security_Services','P3 security boundaries and shared services','Security-edge and shared-service owners','RB-00; approved EC/SE/ZIP and service topology; actual endpoints, paths, identities, protocols, HA and capacity.','RA §§8–13,22; SVC §§1–6; WD §§5–7',[
('Create owned security capacity','Use the selected supported edge mechanism to instantiate isolated contexts/handoffs and separately protected management.','Only permitted domains and routes belong to each context.','Do not import unrelated tenant routes or expose admin interfaces on the consumption path.','Context/interface and writer ownership receipt.'),
('Establish forward/reply paths','Configure accepted prefix and source policy, native gateway handoffs and service-side origin-specific replies.','No connected, neighbour, NAT or alternate default path bypasses enforcement.','Wrong or missing reply path remains unavailable rather than being masked by a broad route.','Routing/FIB and stateful path observation.'),
('Publish named service consumption','Establish actual DNS/time/repository/log/identity endpoints, entitled operations and scoped initiators.','Selected complete protocols work, including applicable DNS TCP/UDP behaviour.','No broad provider subnet or administrative grant for a service binding.','Endpoint/protocol and authorization tests.'),
('Establish key and protection custody','Identify actual key-service client, capture API, data mover, protected copies, catalogue and held-data obligations.','Tenant workloads do not inherit platform capture or key-destruction privileges.','Missing key/catalogue recovery or independent-copy protection blocks the promise.','Role, copy lineage and recovery evidence.'),
('Observe continuity and telemetry','Test approved service/edge outages and restore paths; verify origin attribution, buffering and actual surviving capacity.','Security and service interruption both measured without fallback bypass.','No unsafe fault or reliance on untested caches.','Fault/restore/telemetry and capacity report.'),
('Accept service handoffs','Publish actual endpoints, permitted operations, owners, versions, limits and dependencies to downstream packages.','P2/P3 offered capability is accepted before routine consumption.','Incomplete mandatory service blocks dependent activation.','Service readiness and G2 contribution.')]),
('RB-06','P4_P5_Tenant_and_Activation','P4–P5 qualification fixture, tenant build and activation','Tenant deployment and acceptance owners','RB-00; resolve whether restricted qualification or production. Production requires qualified capacity and applicable initial G4 plus operating authority.','RA §23; WD §§9–11,13; IK §§6–7',[
('Choose the authorized path','Record restricted fixture permission or production prerequisites, exact service envelope and tenant owner.','No production permission inferred from test authorization.','Missing actual authorization stops the affected operation.','Scope-specific gate/test decision.'),
('Reserve eligible resources','Allocate authoritative addresses, capacity, storage and attachment/security slots; establish tenant/domain scope.','One owned reservation per resource; actual allocation recorded.','No guessed values or use of excluded capacity.','Reservations and native scope identities.'),
('Build denied topology','Create owned networks, gateways and baseline policy; coordinate paired edge routes/flows under the edge owner.','No endpoint is exposed before mandatory enforcement.','Unverified partial state remains disconnected/quarantined.','Native topology and policy receipts.'),
('Create protected resources','Instantiate approved images/VMs/disks in eligible pools, then names, service identities, telemetry and protection.','Actual attachments and client/admin boundaries match the LLD.','Do not weaken placement or data custody to complete the request.','As-built resource/protection record.'),
('Observe applicable outcomes','Run scoped healthy-control, permitted/denied, resource/role, family and recovery observations.','Actual results and artifacts recorded separately from expected outcomes.','Unknown/failed mandatory results remain open, not passes.','IT test records and evidence index.'),
('Complete initial readiness and activate','For production, verify G0/G1/G2/current tests, applicable G4 initial and valid operating authority; execute the approved exposure change and verify it.','Only the accepted service scope becomes active.','Failed live verification withdraws exposure without destroying data.','G3 decision, activation/post-check and operations confirmation.'),
('Close or retain the fixture','Retire disposable test resources and reconcile reservations or formally accept the authorized continuing scope.','No stale test permissions or orphan resource.','Hold required evidence/data; do not blind-destroy shared resources.','Residual scan and scope closure.')]),
('RB-07','Failure_and_Change_Recovery','Interrupted execution, adoption and controlled change','Current authoritative resource owner','Approved recovery/change scope; native task visibility; known custody; read access to current state and incident constraints.','RA §25; PROV §§5–6; WD §10',[
('Stabilize ownership','Pause competing changes and establish the actual writer, accepted tasks and incident restrictions.','No second executor makes assumptions about task cancellation.','Do not force-unlock until writer cessation is established by the approved recovery procedure.','Task/writer/lock timeline.'),
('Discover actual effects','Compare native resources, addressing, routes, data and state against the last confirmed step.','Unknown outcomes become explicit owned findings.','Do not replay create blindly or infer failure from a lost response.','Native IDs, task results and semantic difference.'),
('Choose safe repair','Owner approves resume, supported rollback, forward repair or isolated operator intervention with data effects.','Shared resources and newly written/held data are preserved.','No generic compensation may destroy required data.','Recovery decision and bounded action plan.'),
('Revalidate change basis','Replan affected scope when input, policy, state or authority changed; reconcile supported brownfield ownership/import.','No stale plan or dual controller ownership.','Import alone is neither compliance nor permission for replacement.','Fresh plan and ownership handoff.'),
('Execute and observe','Run approved scoped repair; retain containment until its authority releases it; verify impacted paths/data.','Actual desired and realized state converges with supporting evidence.','Unexpected effects stop further changes and trigger escalation.','Repair/task receipts and retests.'),
('Close and improve','Update as-built, source, defects, reservations, custody and runbook lessons.','Unresolved effects remain visible and owned.','Do not rewrite historical approval or hide retained exceptions.','Incident/change closure and revised records.')]),
('RB-08','Data_Recovery_and_Migration','Data recovery, platform exit and controlled failback','Data and recovery authorities','Actual scope, accepted data/copy/key inventory, target design, qualified method, objective boundaries and separately approved exercise/change.','RA §§14,27; SVC §6; WD §§10,12–13',[
('Declare scope and writer authority','Identify failed/source/target systems, consistency requirements and permitted recovery action. Fence ambiguous writers by the accepted mechanism.','One authorized write authority and protected evidence.','Do not promote a second writer while ownership is unresolved.','Fencing and recovery authority record.'),
('Restore minimum dependencies','Recover approved administration, trust, name/time, keys/catalogue and source/configuration access.','Recovery path does not depend solely on the failed platform.','No plaintext, replacement-key or unrestricted privileged fallback.','Dependency health and custody receipts.'),
('Prepare isolated target','Establish eligible compute/data/network boundaries and required services under deny.','Target supports required image/device/data/identity semantics.','Unsupported conversion or co-residency blocks target use.','Target as-built and compatibility checks.'),
('Transfer or restore consistent state','Use the approved platform/data tool through bounded authorized access; preserve copy lineage and measure actual data point.','Useful consistent data is available and attributable.','A completed job is not evidence of useful recovered data.','Transfer/restore logs and integrity/consistency markers.'),
('Verify and reconnect','Check application-owner data acceptance, required security/services and recovery timing before approved DNS/exposure cutover.','Current authority accepts the defined recovered service.','Failed verification keeps target isolated.','Measured RTO/RPO scope and activation record.'),
('Fail back or retire source','Plan reverse synchronization after new writes; remove temporary routes/grants and reconcile retained copies.','No stale writer, uncontrolled transition path or destroyed held key.','Starting an old VM is not automatically safe rollback.','Failback/source-retirement and retained-data receipts.')]),
('RB-09','Retirement_and_Handover','Operational acceptance, retirement and retained obligations','Service operations and data disposition owners','Actual inventory/ownership, consumers, holds, recovery requirements and approved disposition scope.','RA §§26–28; QUAL §7; WD §§9–10,12',[
('Accept actual operations scope','Confirm owner/on-call/support, monitoring, accepted limits, patch/change process, custody and exercised recovery.','Initial readiness supports the production promise.','Missing actual owner or required restore evidence blocks initial acceptance.','IT §6 and initial G4 decision.'),
('Plan retirement and preserve obligations','Identify dependent services/shared resources, held copies and keys; complete required export/backup before revoking required paths.','Every remaining obligation has an accountable owner.','Do not delete service access required to preserve held data.','Disposition plan and copy lineage.'),
('Withdraw live access','Under the relevant owner, remove exposures, ordinary flows, names, routes and grants; confirm session handling.','No obsolete live connectivity/authority remains.','Do not remove another tenant’s shared domain/service.','Native deletion and residual checks.'),
('Remove eligible resources','Delete only owned eligible workload/attachments; quarantine address reuse and preserve required history.','Actual native state and inventory agree.','Unknown asynchronous completion or reuse conflict remains blocked.','As-built retirement and allocation release.'),
('Sanitize approved data/media','Use the approved media-appropriate process through qualified personnel; verify key/copy scope and held exceptions.','Reuse is supported by actual sanitization evidence.','Resource-record deletion is not proof of data destruction.','Sanitization/retention receipt and verification.'),
('Close and continue retained custody','Retain tombstone, evidence, obligations, access/key custody and future review/disposal dates.','Live service retired; residual data remains explicitly controlled.','Do not mark total destruction while copies remain.','Final service/data decision and continuing obligations.')])]
rows=[]
for bid,slug,title,owner,pre,baseline,steps in books:
 p=out/f'{bid}_{slug}.md'
 text=f'''# {bid} — {title}\n\n**Status:** site-parameterized reference method; NOT EXECUTED.\n\n**Owner role:** {owner}. Assign an actual owner before use.\n\n**Baseline:** {baseline}. [Main architecture](../../05_Reference_v1_4/00_Reference_Architecture_v1_4.docx) · [Worked design](../../05_Reference_v1_4/07_Worked_Infrastructure_Design_and_Acceptance_v1_4.docx) · [Execution record](../MOP_Test_and_Handover_Template.docx).\n\n## Required inputs\n\n{pre}\n\nEnter the actual site/service/tenant scope, design revision, exact supported component/API/provider/installer tuple, configuration artifact and protected credential reference. Every step must have an actual executor, completion signal, timeout/retry rule, observation, stop condition, data-safe recovery action and evidence location. No production address, credential, product count or universal native command is supplied.\n\n## Controlled method\n\n'''
 for i,(name,action,expected,stop,evidence) in enumerate(steps,1):
  sid=f'{bid}-{i:02d}'
  text+=f'### {sid} — {name}\n\n**Action:** {action}\n\n**Expected observation:** {expected}\n\n**Stop / preserve:** {stop}\n\n**Evidence:** {evidence}\n\n**Actual artifact / operator / UTC times / native task / outcome:** NOT RUN — complete in IT §2 and the implementation workbook.\n\n'
  rows.append(dict(step_id=sid,runbook=bid,owner_role=owner,title=name,action=action,expected=expected,stop=stop,evidence=evidence,status='Not run',baseline=baseline,actual_artifact='',actual_owner='',actual_evidence=''))
 text+='## Completion and restart\n\nThe designated owner reviews actual observations and unresolved effects before the next package consumes the result. A failed or unknown operation stays owned and restricted until reconciled. Do not restore an old state file and describe it as rollback of infrastructure. Production activation requires the applicable initial operational/recovery readiness and valid operating authority; a restricted fixture cannot supply that authority.\n\nThese methods extend the baseline as proposed kit practice. They do not change the frozen source requirements or provide executable vendor adapters.\n'
 p.write_text(text,encoding='utf-8')
csvwrite(ROOT/'04_Shared/build_step_catalogue.csv',list(rows[0]),rows)
(ROOT/'source/runbook_catalogue.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False))
print(f'Wrote {len(books)} runbooks and {len(rows)} reference steps')
