from doc_engine import Book
from catalogue import DATA

def build_delivery():
 b=Book('DEL');heads=[(1,'Three kits, one controlled delivery'),(2,'Deliverable ownership and handoffs'),(3,'Acceptance gates and restricted qualification'),(4,'Working records, examples and evidence'),(5,'Review sequence and change control'),(6,'Inputs still required for an actual deployment')]
 b.front('Architecture decides. Engineering specifies. Implementation proves and hands over.', 'Start here, then use the role kit and its editable template. The architecture stays infrastructure-led; automation is an implementation choice inside the approved ownership and lifecycle boundaries.', heads)
 b.page(1,heads[0][1], 'These kits extend the v1.4 library without changing its eight baseline documents. The kit version is independent of the reference-architecture version. A proposed delivery record does not amend an adopted architectural requirement.', [('RA',1),('RA',30),('WD',9)])
 b.table(['Kit','Primary question','Exit artifact'],[
 ('Architecture','What is required, why, where are the boundaries, and what may be shared?','Reviewed high-level design (HLD), decisions, service envelope, selected controls and engineering handoff.'),
 ('Engineering','Exactly how will this site and selected stack realize the approved design?','Reviewed low-level design (LLD), resource/path schedules, calculations, support tuple and build/test package.'),
 ('Implementation','How will the approved configuration be established, verified, activated and operated?','Executed method of procedure (MOP), observed test/evidence records, as-built configuration and accepted handover.')],[1.15,2.80,3.19])
 b.h('How the work connects')
 b.p('Carry a stable requirement or decision ID into the engineering schedule, then into a work-package step, a verification assertion and the resulting evidence. Retain actual resource IDs only in the controlled engineering and as-built records. A diagram must use the same component and interface identities as the schedules.')
 b.p('A normal first delivery selects one hosting stack, plus all required physical, security and shared-service integrations. Repeat the same service outcomes on the other stacks for separate portability qualification. A simultaneous split-stack deployment is a different, explicitly designed service.')
 b.note('Included scope: architecture, detailed engineering, commissioning, tenant delivery, qualification, recovery, operations and retirement. Excluded: fabricated site approvals, guessed native configuration, live deployment, and a mandatory custom controller.')
 b.page(2,heads[1][1], 'The kit deliverable IDs identify working outputs; they do not renumber the 194 baseline requirements. Use the shared deliverable catalogue as the handoff checklist.', [('AK',1),('EK',1),('IK',1)])
 for discipline,short in [('Architecture','AK'),('Engineering','EK'),('Implementation','IK')]:
  b.h(discipline)
  ds=[d for d in DATA['deliverables'] if d['discipline']==discipline]
  b.p('; '.join(d['id']+' '+d['title'] for d in ds)+'.')
 b.table(['Handoff','Sender must supply','Receiver must verify'],[
 ('Architecture → engineering','Adopted scope, decisions, sharing matrix, requirements and service constraints.','No conflicting boundaries or unresolved decision that affects the proposed build.'),
 ('Engineering → implementation','Controlled revision, site schedules, exact tuple, reviewed MOP and evidence plan.','No guessed addresses, default credentials, competing writers or unsupported required operation.'),
 ('Implementation → operations','Actual topology, configuration, observed tests, support, recovery and retained obligations.','The delivered scope can be supported and recovered; required readiness existed before production activation.')],[1.45,2.80,2.89])
 b.page(3,heads[2][1], 'Gate numbers are identifiers, not an automatic chronological ladder. v1.4 requires applicable initial G4 readiness before G3 production activation. Qualification can use a separately authorized non-production fixture before G2 is complete.', [('WD',9),('QUAL',5)])
 b.table(['Decision','Required preceding condition','Prohibited shortcut'],[
 (g['id']+' — '+g['purpose'],g['prerequisites'],g['limit']) for g in DATA['gates']],[1.56,2.90,2.68])
 b.p('A gate record names the actual service/site/version scope, decision authority, evidence and conditions. Failed or missing evidence cannot be converted into acceptance merely by changing a spreadsheet status. Applicability decisions also require an accountable rationale.')
 b.page(4,heads[3][1], 'Use one controlled site record set; do not maintain independent conflicting versions in every team. The three workbooks are working registers. Shared CSVs are reference snapshots unless explicitly designated as the project record.', [('RA',28),('WD',13)])
 b.table(['Material','Treatment','Where to work'],[
 ('Frozen reference documents','Read and cite; retain original bytes and record variations separately.','05_Reference_v1_4/'),
 ('Kit guides','Instructions, quality criteria and boundary conditions.','Each role directory'),
 ('Word templates','Copy for a named project; complete the tagged response controls and attach actual diagrams.','HLD, LLD and MOP/test/handover templates'),
 ('Workbooks','Enter actual owners, approved values and evidence. Example-labelled sheets are not site allocations.','Architecture_Registers, Engineering_Schedules, Implementation_Tracker'),
 ('Runbooks','Adapt to the reviewed LLD, product tuple and approved change window before execution.','03_Implementation/runbooks/'),
 ('Local tools','Package/link checking and a limited offline Terraform plan review; no infrastructure access.','06_Tools/'),
 ('Evidence','Store approved artifacts in the controlled repository; record IDs, hashes, scope and collection times.','Implementation evidence register; not unprotected logs in email.')],[1.35,3.12,2.67])
 b.h('Status discipline')
 b.p('Separate design completion, engineering review, installation, technical qualification, operational readiness and authorization. “Not run”, “unknown” and “not applicable” are distinct. A plan, receipt or signature-reference string is not proof that the underlying control or authority exists.')
 b.page(5,heads[4][1], 'Use focused reviews at the point where a decision becomes expensive to reverse. Do not use document length or a green dashboard as the quality measure.', [('RA',25),('RA',29),('QUAL',7)])
 b.table(['Review','Questions to settle','Attendees / resulting record'],[
 ('Architecture workshop','Scope, boundaries, sharing, service classes, alternative realizations and exit constraints.','Architecture, security, platform, network, storage and service owners; AK-01–08.'),
 ('Engineering walkthrough','Trace one allowed and one denied path; lose one component; restore one dataset; adopt one existing resource.','Detailed-design owners and operators; EK-01–09 with discrepancies assigned.'),
 ('Change rehearsal','Validate artifact identity, least privilege, one-writer ownership, safe stop, late tasks and recovery.','Implementers, change authority and assurance; reviewed MOP.'),
 ('Qualification review','Assess actual assertion coverage, limits, negative controls and scoped evidence.','Independent reviewer where required; G2 disposition, not production permission.'),
 ('Readiness / activation','Confirm support and required restore proof, operating authority and current tenant checks.','Service, operations, data/security authorities; initial G4 then G3.'),
 ('Post-change / ongoing','Capture as-built differences, residual defects, measurement trends, expiry and renewed tests.','Operations and lifecycle owners; continuing G4 and change impact.')],[1.40,3.18,2.56])
 b.p('If a requirement or topology changes, identify affected decisions, engineering schedules, modules/configurations, test cases, service promises and deployed environments. Record whether the change is a variation, a new service class or a revision to the adopted architecture. Retain the former baseline and actual historical decision.')
 b.page(6,heads[5][1], 'The kits are complete as reusable working material. An actual build still needs the following inputs from the responsible people and systems; no value is inferred from an example.', [('GM',4),('WD',14)])
 b.table(['Input','Owner to supply it','Blocks'],[
 ('Named site, cells, equipment and actual physical failure groups','Site, facility and platform owners','G1 detailed physical commissioning'),
 ('Approved zone/co-residency and management separation','Architecture and security authority','Affected host, storage and privileged paths'),
 ('Exact hardware, firmware, software, API, provider and entitlement combination','Platform/network/service engineering','G2 support and capability qualification'),
 ('Actual IP/DNS, routing, ZIP and service handoffs','Network/security/service owners','Dependent path construction and activation'),
 ('Service targets, capacity, retention, keys and location constraints','Service/data/security owners','Advertising the offered service'),
 ('Native automation and installation/configuration artifacts','Assigned technical owners','Execution of supported P0–P6 operations'),
 ('Real observations, evidence and operating authority','Assurance, operations and designated approvers','G2, initial G4 and production G3')],[2.66,2.49,1.99])
 b.p('Scope special devices, bare metal, container hosting, public access, L2 stretch or cross-stack composite services separately. The base VM-oriented kit provides the interface and acceptance pattern, not unqualified implementations of these extensions.')
 b.note('Start by assigning the architecture owner, completing AT §1 and marking requirement applicability. Engineering can investigate options in parallel, but must not treat an unresolved architecture choice as an approved build parameter.')
 b.save()

def build_ak():
 b=Book('AK');heads=[(1,'Architecture work plan and definition of done'),(2,'Service requirements and applicability'),(3,'Required architecture views'),(4,'Security, management and co-residency decisions'),(5,'Service resilience, capacity and portability'),(6,'Vendor realization and provisioning strategy'),(7,'Decisions, risk and review'),(8,'Engineering handoff and change impact')]
 b.front('Build the decision baseline before selecting configuration values.', 'Use this guide with the HLD template and Architecture_Registers.xlsx. The guide defines the work; the template captures the resulting design; the workbook tracks ownership, applicability and unresolved decisions.',heads)
 b.page(1,heads[0][1], 'The architect owns the coherence of the whole hosting service, not a Terraform repository or a custom application. The design must explain what exists, how it connects, which parties control it and what happens during change or failure.', [('RA',1),('RA',3),('AT',1)])
 b.table(['Work','Input','Output / review'],[
 ('Frame the service','Demand, beneficiaries, information envelope, current estate and constraints.','AK-01 with explicit exclusions and stakeholders.'),
 ('Select obligations','Reference requirements, applicable source editions, service targets and inherited controls.','AK-02 with owner, applicability and verification.'),
 ('Develop linked views','Physical/logical components, boundaries, resources, flows and dependencies.','AK-03 with IDs that persist into engineering.'),
 ('Resolve decisions','Viable options, security/resilience consequences, costs and exit effects.','AK-04–07; proposed versus actually adopted choices distinguished.'),
 ('Review and release','Cross-discipline walkthrough, unresolved risks and necessary authority.','AK-08; accepted handoff or specific blocking gaps.')],[1.5,2.8,2.84])
 b.h('Definition of done')
 b.p('A reviewer can trace an allowed flow and its reply, explain why an alternative path is blocked, locate the management and storage boundaries, understand the sharing decision, and identify the exact engineering records still required. Unknown site values are assigned—not hidden as product defaults.')
 b.note('Do not accept a drawing that is only a list of products. Do not call a collection of API object definitions the infrastructure architecture.')
 b.page(2,heads[1][1], 'Start with the required service and information context, then select topology and capability. Keep security categorization separate from uptime, recovery objectives and performance.', [('RA',2),('RA',14),('AT',2)])
 b.table(['Requirement group','Decisions to record'],[
 ('Service and ownership','Service/data/security owners, tenants, workloads, operating support model and excluded responsibilities.'),
 ('Security and placement','Independent confidentiality, integrity and availability impact; zone authority; allowed sharing; location/access and key custody.'),
 ('Resource and connectivity','Compute profiles, block/file/object needs, identity dependencies, allowed flows, external services and exposure.'),
 ('Reliability','Measurement endpoint/window, interruption treatment, failure set, RTO/RPO scope, consistency and restoration acceptance.'),
 ('Lifecycle','Growth, maintenance, migration/exit, support horizon, retention, disposal and operating ownership.'),
 ('Evidence and applicability','Each selected requirement maps to its design home, control owner, verification method and exception policy.')],[1.65,5.49])
 b.p('The workbook preserves all 194 inherited requirement statements as reference text. It does not automatically adopt them for a new project. For each row choose applicable, not applicable with rationale, or unresolved; retain the exact source identifier and edition when assigning selected controls.')
 b.p('The current ITSP.10.033 introduction explicitly supersedes ITSG-33 Annex 3A. Keep any legacy assessment linkage version-aware; do not infer that matching control numbers establish equivalence. [K02]')
 b.external(['K02']);b.note('Acceptance test: no offered service depends on a mandatory requirement whose owner, applicability or implementation boundary is still unknown.')
 b.page(3,heads[2][1], 'Create views that answer distinct questions but share component and interface IDs. Combine diagrams where useful; completeness is coverage, not a required count of separate drawings.', [('RA',3),('RA',10),('AT',3)])
 b.table(['View','Question / minimum contents'],[(v['id']+' '+v['view'],v['question']+' '+v['required_content']) for v in DATA['views']],[1.85,5.29])
 b.p('Use a legend for data, management and dependency relationships. Show administrative and failure boundaries separately from routing boundaries. Identify shared equipment explicitly. A redundant icon does not establish independent power, storage, controller, uplink or key dependencies.')
 b.page(4,heads[3][1], 'Record the security decision at every shared layer. Separate a tenant name, a zone class, an independently governed zone/domain and the native routing object that realizes it.', [('RA',6),('RA',7),('RA',8),('AT',7)])
 b.table(['Layer','Question that must be answered'],[
 ('Compute and hypervisor','Which domains may share a host or cluster, and do placement, evacuation and HA restart preserve that decision?'),
 ('Storage and protection','Are disks, controllers, replicas, copies, key scopes or backup administrators shared? What prevents cross-scope attachment and destruction?'),
 ('Routing and ZIP','Which two authorities approve a relationship? Where are forward/reply traffic and required inspection enforced?'),
 ('Management and OOB','Which authority can administer each target? Does emergency access survive the specific production failure?'),
 ('Shared services','Is consumption distinct from management and backend entitlement? Can a compromised service abuse permitted sessions?'),
 ('Automation and supplier access','Who can change native resources, where do credentials operate, and how are temporary privileges and diagnostics controlled?')],[1.67,5.47])
 b.p('Retain the v1.4 zone-aware host-pool baseline and explicit alternative approval. “Same RZ label” alone does not justify co-residency. “Dedicated” must identify which of host, cluster, storage, edge, management, backup and key custody is actually dedicated.')
 b.p('Cloud zoning guidance distinguishes logical ZIP functions and management-connected versus data-path interfaces; a product object by itself is not the whole control design. The kit uses that as source context, not as a substitute for an adopted control profile. [K01]')
 b.external(['K01'])
 b.page(5,heads[4][1], 'Specify the service promise before calculating equipment. The engineering team then proves feasibility using the actual component combination and a common failure/load basis.', [('RA',14),('RA',26),('RA',27),('AT',8)])
 b.table(['Architectural decision','Engineering evidence it drives'],[
 ('Covered failure set','Enumerated nodes/racks/links/partitions and common dependencies; available survivor capacity under each case.'),
 ('Service indicator and error treatment','Explicit measurement boundary, success criterion, window, maintenance accounting and alert owner.'),
 ('Recovery objective','RTO start/end, recoverable consistency point for RPO, key/catalogue dependencies and isolated acceptance.'),
 ('Data/control location and access','Locations of primary data, copies, logs, diagnostics, managers, support and keys, separately recorded.'),
 ('Capacity on demand','Commissioned service-class capacity, reservations, expansion lead time and blocking bottlenecks—not merely free cores.'),
 ('Portability and exit','Alternative-platform build, disk/data conversion limits, identity/key rebinding, support/skills and observed recovery.')],[1.73,5.41])
 b.p('Portability has distinct claims: equivalent deployment, simultaneous composite use and migration of workload/data state. Qualify the specific claim. The same logical request on two platforms does not prove safe live migration or identical backup formats.')
 b.note('Decision quality check: the architecture states what must survive and recover, while the LLD names the actual resources that provide it. Missing evidence results in an excluded or unqualified service capability, not an invented guarantee.')
 b.page(6,heads[5][1], 'Describe the native realization before deciding the automation structure. Select an owned work package for every resource family and a supported execution mechanism for each lifecycle operation.', [('RA',15),('RA',20),('RA',24),('AT',9)])
 b.table(['Realization','Architectural responsibilities to retain'],[
 ('Nutanix','AHV/AOS and Prism/Flow responsibilities; distinct project/RBAC, VPC routing, protected selectors, external handoff and data/protection scope.'),
 ('VMware/NSX','ESXi/vCenter placement and data integration; distributed versus service routing; Tier-1 and isolated upstream/Edge path; provider policy hierarchy.'),
 ('OpenStack','Distribution/controller responsibilities; Keystone/Nova/Placement/Neutron/Cinder; chosen backend; provider-owned baseline network mutation.'),
 ('Common infrastructure','Fabric and OOB, ZIP/security contexts, IPAM/DNS, identity/keys, logging, images and backup remain independently owned integrations.')],[1.35,5.79])
 b.h('P0–P6 as infrastructure work')
 b.p('P0 establishes trusted bootstrap; P1 commissions physical transport and recovery access; P2 installs native platforms; P3 establishes shared services and security boundaries; P4 allocates tenant/domain infrastructure; P5 creates workload resources and controlled service activation; P6 maintains, recovers, migrates and retires.')
 b.p('Terraform manages supported resources through qualified APIs. Platform installers, firmware tooling, backup products and other service mechanisms retain their native lifecycle responsibilities. An unsupported provider operation needs a named alternative and accepted handoff; it is not solved by an empty module.')
 b.refs([('VC',1),('IK',2)])
 b.page(7,heads[6][1], 'Use an architecture decision record for choices with material consequences. A decision records why an option is suitable for the offered scope, not merely that a product has a feature.', [('RA',29),('GM',4),('AT',6)])
 b.table(['Decision record','Minimum evidence'],[
 ('Problem and constraints','Business/service need, threat/failure assumptions, affected requirements and scope.'),
 ('Viable alternatives','At least the realistic alternatives or a clear explanation of why no alternative meets the constraints.'),
 ('Selected design','Components, boundary/authority model, integration interfaces and required capabilities.'),
 ('Consequences','Security, availability, complexity, capacity/cost, operations, portability and exit limitations.'),
 ('Authority and validity','Proposed/accepted/rejected status, actual decision owner, date, applicable scope and review triggers.'),
 ('Follow-through','LLD schedule IDs, build ownership, qualification assertions, remaining blockers and superseded decisions.')],[1.65,5.49])
 b.p('The risk register separates a design concern from an observed implementation defect. A proposed mitigating control remains proposed until implemented and evidenced. Risk acceptance records residual risk and conditions; it does not assert the missing control exists.')
 b.h('Review challenge')
 b.p('Ask another discipline to identify the broadest route, most privileged credential, largest shared failure domain, weakest return-path assumption and hardest recovery dependency. Resolve the answer in the design and records rather than adding another generic assurance statement.')
 b.page(8,heads[7][1], 'Release the architecture only with a clear contract for engineering: decisions made, decisions delegated, prohibited shortcuts and evidence needed at each gate.', [('RA',30),('QUAL',2),('AT',10)])
 b.table(['Handoff item','Quality condition'],[
 ('Scope and source baseline','Reference release, adopted obligations, selected service classes and excluded extensions identified.'),
 ('Views and IDs','Physical/logical/security/resource/provisioning views use consistent component and interface identities.'),
 ('Selected decisions','Sharing, routing, security-edge, management, data, recovery and platform variations have actual dispositions.'),
 ('Required engineering schedules','Specific resource, port, address, route, flow, identity, storage, capacity and tool records assigned to owners.'),
 ('Verification design','Each material requirement can be inspected, tested or independently assessed at an identified stage.'),
 ('Unresolved issues','A named owner, blocking gate, due/review trigger and closure evidence exist for each unresolved choice.')],[1.64,5.50])
 b.p('Changes to the adopted architecture require impact review across all dependent engineering and implementation records. A change only to a site address may remain LLD scope; a change to zone sharing, required enforcement, recovery promise or supported service envelope requires architecture/security review.')
 b.note('Architecture kit completion: AK-01–AK-08 reviewed and handed over. This is G0 design adoption for a defined scope—not proof of platform support, commissioning or authorization to operate.')
 b.save()

def build_at():
 b=Book('AT');heads=[(1,'Mandate and service envelope'),(2,'Requirements and applicability'),(3,'Context and physical deployment views'),(4,'Logical tenancy, security and traffic views'),(5,'Management, data and service dependencies'),(6,'Architecture decision record'),(7,'Threat, sharing and responsibility review'),(8,'Reliability, capacity and exit design'),(9,'Vendor realization and provisioning strategy'),(10,'Architecture review and engineering handoff')]
 b.front('Editable high-level design record. Copy once per adopted service/site scope.', 'Enter responses in the tagged fields; attach the actual drawings and controlled register snapshots. Do not copy illustrative addresses or mark unknown evidence as complete. Repeat a page or schedule where multiple decisions require separate records.',heads)
 pages=[
 (1,'AK-01', [('Service identity','Name, scope/version and intended consumers.','AT_SERVICE'),('Accountable owners','Actual service, data, architecture and security decision owners.','AT_OWNERS'),('Need and demand','Problem, current limitations, forecast demand and operating model.','AT_NEED'),('Information envelope','Separate confidentiality, integrity and availability impact; exclusions.','AT_CATEGORY'),('Service envelope','VM/data/network services, supported families, public/partner extensions and exclusions.','AT_ENVELOPE'),('Constraints','Location, support, budget/time, lifecycle and existing dependencies.','AT_CONSTRAINTS')], 'Reviewer: scope is bounded, owners are named, and unsupported or higher-sensitivity services are not silently included.', [('RA',1),('RA',2)]),
 (2,'AK-02',[('Source baseline','Reference release and exact adopted standards/control-profile editions.','AT_BASELINE'),('Requirements register','Controlled workbook/revision and selected requirement IDs.','AT_REQS'),('Applicability rationale','Applicable, excluded or unresolved items with authority and reason.','AT_APPLICABILITY'),('Control responsibility','Provider, tenant/shared/inherited obligations; evidence owner.','AT_CONTROL'),('Acceptance outcomes','Required observable outcomes and stage of verification.','AT_ACCEPT'),('Unresolved obligations','Issue IDs, owner, blocking gate and required decision/evidence.','AT_REQ_GAPS')], 'Reviewer: no selected requirement is ownerless; family-level mappings are not represented as a completed control assessment.', [('RA',28),('QUAL',6)]),
 (3,'AK-03',[('V01 context','Attach a view of consumers, providers, external authorities and offered service boundary.','AT_V01'),('V02 physical view','Attach sites, cells, host/storage/edge/control roles and main links.','AT_V02'),('Failure dependencies','Identify shared racks, power, links, managers, storage and trust services.','AT_FAILURES'),('Physical sharing','State physical dedication versus logical separation per component role.','AT_PHYSICAL'),('External dependencies','Owner, service interface and availability/approval boundary.','AT_EXTERNAL'),('Assumptions','Unconfirmed inventory/topology assumptions and who must resolve them.','AT_ASSUMPTIONS')], 'Reviewer: redundant symbols have explicit failure assumptions; a hosting cell is not automatically an independent failure domain.', [('RA',3),('RA',4)]),
 (4,'AK-03',[('V03 logical view','Tenants, WSDs, logical domains and site/platform instances with authorities.','AT_V03'),('V04 path view','One approved flow and reply; one denied cross-tenant path; shared-service path.','AT_V04'),('Boundary relationships','Two adjacent authorities, ZIP functions, default policy and approval ownership.','AT_ZIPS'),('Bypass analysis','Native routing, shared segments, extra NICs, NAT, alternate families and failure paths.','AT_BYPASS'),('Exposure model','Public, enterprise/partner and egress mediation; none unless explicitly selected.','AT_EXPOSURE'),('Path schedule reference','Engineering flow/route records that will implement these views.','AT_PATH_REF')], 'Reviewer: every required trust transition has forwarding and enforcement explained; same zone class does not imply shared reachability.', [('RA',7),('RA',8),('WD',6)]),
 (5,'AK-03/05',[('V05 administration','Privileged origin, management boundaries, actual authority and emergency path.','AT_V05'),('V06 compute/data','Host pools, virtual-disk and guest-data paths, copies, storage control and key scope.','AT_V06'),('V07 services','Consumption interface, initiating client, reply path and backend entitlement.','AT_V07'),('Bootstrap dependencies','Services needed before platform APIs exist and transfer to steady state.','AT_BOOTSTRAP'),('Trust/copy custody','Separate use, administration, recovery and disposal responsibilities.','AT_TRUST'),('Dependency register','Controlled record locating inherited services and shared failure impacts.','AT_DEPENDENCIES')], 'Reviewer: guest storage encryption does not invent a guest KMS route; backup orchestration and data movement are separate paths.', [('RA',6),('RA',12),('RA',13),('SVC',1)]),
 (6,'AK-04',[('Decision identity','ID, scope, status and version of the decision.','AT_ADR_ID'),('Problem/constraints','Why this choice is needed and affected baseline requirements.','AT_ADR_CONTEXT'),('Alternatives','Viable mechanisms and rejection rationale, not a vendor popularity ranking.','AT_ADR_OPTIONS'),('Proposed selection','Chosen topology/control placement and conditions of use.','AT_ADR_CHOICE'),('Consequences','Risks, capacity/cost, management, recovery, support and portability.','AT_ADR_EFFECT'),('Decision authority','Actual decision, approver/date/reference, conditions and review triggers.','AT_ADR_APPROVAL'),('Downstream links','LLD records, work packages, tests, gaps and superseded decisions.','AT_ADR_LINKS')], 'Default decision state is PROPOSED. A completed template does not issue organizational adoption or authorization.', [('RA',29),('GM',4)]),
 (7,'AK-05',[('Threat/failure assumptions','Compromised workload/admin/host/service, misconfiguration, outage and partition scope.','AT_THREATS'),('Co-residency matrix','Allowed sharing per host, cluster, storage, edge, management, backup and keys.','AT_SHARING'),('Mandatory enforcement','Control location, owner and behaviour during failure/change.','AT_ENFORCEMENT'),('Residual risk','Remaining risk, affected service and actual accepting authority/conditions.','AT_RESIDUAL'),('Inherited controls','Source service, evidence scope/time and inherited versus tenant obligation.','AT_INHERIT'),('Sensitive lifecycle','Support access, diagnostics, copies, retention and disposition authority.','AT_LIFECYCLE')], 'Reviewer: a label or logical segmentation claim is not proof of physical independence or protection against privileged compromise.', [('RA',6),('RA',7),('QUAL',6)]),
 (8,'AK-06',[('V08 failure/recovery view','Covered failure set, survivors, quorum, fencing and recovery site dependencies.','AT_V08'),('Service measurement','Indicator, observation boundary/window and maintenance treatment.','AT_SLO'),('Recovery measurement','RTO start/end, RPO consistency point and useful-data acceptance.','AT_RECOVERY'),('Capacity strategy','Demand, shared resource bottlenecks, operational reserve and expansion triggers.','AT_CAPACITY'),('Location/control','Primary/copy/log/diagnostic/control/admin/key restrictions and authorities.','AT_LOCATION'),('Exit feasibility','Target options, conversion limits, key/identity dependencies and rehearsal evidence needed.','AT_EXIT')], 'Reviewer: impact classification is not an uptime promise; every offered recovery promise has a corresponding qualification and initial-readiness condition.', [('RA',14),('RA',26),('RA',27)]),
 (9,'AK-07',[('V09 native realization','Selected stack and alternative candidates with reasons and capability gaps.','AT_V09'),('V10 provisioning view','P0–P6 resources, dependencies, owners and accepted handoffs.','AT_V10'),('Tool boundaries','Terraform/native installer/configuration/protection responsibilities by operation.','AT_TOOLS'),('Bootstrap and adoption','New-site or brownfield sequence, one-writer handover and temporary dependencies.','AT_ADOPTION'),('Controlled activation','Restricted qualification versus production; required G2 and initial G4 evidence.','AT_GATES'),('V11 operational transition','Delivery waves, capacity, ownership, migration and retirement interfaces.','AT_V11')], 'Reviewer: the strategy provisions the whole infrastructure service, not only VMs, and does not require a bespoke controller.', [('RA',15),('RA',20),('RA',24),('WD',9)]),
 (10,'AK-08',[('Review scope','HLD revision, drawings, requirement/decision register snapshots and reviewer roles.','AT_REVIEW'),('Review findings','Blocking items and accepted dispositions with owners and evidence.','AT_FINDINGS'),('Engineering inputs','Actual decisions delegated to LLD, records required and boundary constraints.','AT_HANDOFF'),('Adoption decision','Actual G0 decision/reference, authority, date and limited scope.','AT_G0'),('Conditions/review date','Conditions before further gates, expiry and material-change triggers.','AT_CONDITIONS'),('Receipt acknowledgement','Engineering owner and date acknowledging complete controlled inputs.','AT_RECEIPT')], 'No acceptance is prefilled. When any mandatory decision is unresolved, identify the blocked scope instead of signing a blanket approval.', [('RA',30),('EK',1)])]
 for n,ids,rows,review,refs in pages:
  b.page(n,heads[n-1][1],f'Working record for {ids}. Complete the responses and attach the referenced evidence or drawing; do not replace an unresolved item with an unsupported assumption.',refs)
  b.inputs(rows);b.note(review)
  b.p('Record status: Draft / In review / Accepted for stated scope / Returned for revision. Use the actual review record, not this prompt, as authority.',style='Caption')
 b.save()

if __name__=='__main__':build_delivery();build_ak();build_at()
