from doc_engine import Book
from catalogue import DATA

b=Book('IK')
titles=['Implementation workplan and required inputs','Work packages, dependencies and authority','Staging, bootstrap and physical commissioning','Native platform commissioning tracks','Shared security, services and protection','Restricted qualification and meaningful observations','Tenant provisioning and controlled production activation','Interrupted work, brownfield adoption and change','Operational handover, recovery, migration and retirement']
b.front('Run the accepted design; record the actual result.','Use this kit after a controlled engineering release. The runbooks identify actions and evidence, while the approved site method supplies exact native commands and configuration. No runbook in this kit is authority to change an environment.',list(enumerate(titles,1)))
b.page(1,titles[0],'Implementation converts a reviewed design into an observed, supportable service. Installation, qualification, production activation and continuing operation are distinct outcomes.',[('DEL',3),('EK',8),('WD',9)])
b.table(['Implementation output','Accountable role','Completion evidence'],[(x['id']+' — '+x['title'],x['owner_role'],x['acceptance']) for x in DATA['deliverables'] if x['discipline']=='Implementation'],[2.23,1.48,3.43])
b.p('Use Implementation_Tracker.xlsx for the execution record. A local workbook status is an index to evidence and authority; it is not an approval engine. Record actual operators and approvers rather than accepting the role names in this reference as assignments.')
b.page(2,titles[1],'Maintain separate execution scopes even when one delivery workflow coordinates the whole environment. Handoffs pass only the identities, capacity and configuration facts the next owner needs.',[('RA',20),('PROV',1),('WD',10)])
b.table(['Package','Execute and observe','Accepted handoff'],[
('P0 — bootstrap','Establish restricted administration, minimum time/name/trust and recoverable tooling.','Accountable temporary dependencies; usable recovery access and custody.'),
('P1 — foundation','Commission the accepted hardware, OOB, fabric and attachment capacity.','As-built physical links, routing, MTU, fault behaviour and available slots.'),
('P2 — platform','Install the chosen supported stack; configure eligible compute, storage and transport.','Exact tuple, native ownership, baseline and service limitations.'),
('P3 — services','Establish security contexts, names, identity, keys, logging and protection.','Published consumption interfaces, return paths and protection/custody.'),
('P4 — tenant/domain','Allocate entitled scope, addresses, domains, networks and mandatory policy.','Native identities, eligibility and boundaries under deny.'),
('P5 — resources/activation','Create owned VMs/disks, bind services, verify and activate within authority.','Current test evidence, initial operational readiness and accepted live path.'),
('P6 — lifecycle','Maintain, expand, recover, migrate or retire under the owning scopes.','Changed as-built records, requalification and retained-data obligations.')],[1.35,2.90,2.89])
b.note('P2 installation can depend on accepted P0 bootstrap services. Complete P2/P3 offered-service acceptance together before ordinary tenant allocation. Record and retire temporary trust deliberately; do not create a circular recovery dependency.')
b.page(3,titles[2],'Use RB-00 and RB-01. Staging is part of implementation readiness, not evidence that equipment has been commissioned.',[('RA',21),('ET',2),('PROV',2)])
b.table(['Checkpoint','Required action and observation','Stop condition'],[
('Release and scope','Match change authorization, exact inventory, LLD revision, signed/checksummed artifacts and permitted window.','Unapproved change, inconsistent inventory or unknown resource owner.'),
('Site safety and physical work','Have qualified personnel perform installation using approved facility and manufacturer procedures. Record completion, access, rack/power/failure-group and cable results.','Missing facility release, unsafe conditions or installation outside the accepted design.'),
('Supply and baseline','Verify received equipment, licenses, support, firmware/driver compatibility and trusted software source. Retain media/part custody where required.','Unknown support combination, altered artifact or unaccounted component.'),
('Restricted management','Establish the approved console/OOB and initial privileged trust; restrict target access and register temporary grants.','Default credentials or a tenant path exposes privileged management.'),
('Minimum dependencies','Verify trusted time/name/identity or approved emergency alternatives, certificate trust and artifact access.','Required dependency has no accepted endpoint or independent recovery method.'),
('Foundation observation','Use the approved configuration mechanism; observe links, control policy, MTU, allowed adjacency and surviving access.','Unexpected route/port, missing policy or failed recovery access.'),
('Handover','Store actual configuration, ownership, recovery copy, telemetry and open deviations; obtain G1 scope acceptance.','Required observations absent or unresolved critical deviations.')],[1.28,3.79,2.07])
b.p('Do not store production secrets in this kit. Record a protected custody reference and the authorized role. A temporary bootstrap credential is not a permanent exception to separation of duties.')
b.page(4,titles[3],'Use the selected vendor track, not all three stacks simultaneously by default. The same reference service is repeated on the next stack to establish a separate portability claim.',[('VC',2),('VC',3),('VC',4),('RA',22)])
b.table(['Track','Native installation and preparation','Required observations'],[
('Nutanix / RB-02','Supported AHV/AOS and Prism installation; chosen Flow networking/security; eligible host/controller/storage scope and isolated external handoffs.','Actual VPC/external routing and policy; same-host enforcement; no shared-connected bypass; storage, key and controller dependencies.'),
('VMware/NSX / RB-03','Supported vCenter/ESXi and storage; NSX management, transport/Edge topology, independent domain and upstream contexts.','Actual distributed and service-router paths; gateway mode compatibility; no unauthorized route propagation; DFW ownership and Edge failure behaviour.'),
('OpenStack / RB-04','Selected distribution services, databases/messaging, Keystone/Nova/Placement, Neutron backend, Glance/Cinder and offered services.','Scheduler constraints; provider-owned mandatory network mutation; additive group behaviour; distributed paths, gateway and storage dependencies.')],[1.35,2.96,2.83])
b.h('Common platform receipt')
b.p('Record product, API, provider and installer versions; firmware/drivers and hardware; enabled features and entitlements; control and storage placement; resource identity and authoritative writer; accepted management and data paths; actual tests; limitations; and supported upgrade/recovery approach.')
b.p('Terraform starts at the supported resource API boundary. A native installer can remain the owner of platform installation, upgrades or controller-managed objects. Do not import or directly edit backend objects owned by another control system merely to make every step appear to be Terraform.')
b.note('A documented vendor feature is not a qualified tuple. KIT-TN-01 adds an explicit NSX parent-gateway mode compatibility check; apply it to the selected release before choosing a Tier-0 VRF realization.')
b.external(['K05','K06','K07','K08','K09'])
b.page(5,titles[4],'Use RB-05. Shared services and ZIP capacity are provider infrastructure, not incidental tenant modules.',[('RA',9),('RA',12),('SVC',1),('WD',7)])
b.table(['Service boundary','Commissioning observation','Receipt / responsible owner'],[
('EC/SE and domain handoffs','Correct context membership, permitted prefixes, connected routes, forward/reply symmetry, no alternative inspection bypass; management separately controlled.','Context/interface identities, policies, capacity and test traces / security-edge owner.'),
('Names, addresses and time','One authoritative allocator per delegated scope; forward/reverse lifecycle and reuse; DNS UDP/TCP and fallback; selected time service.','Allocations, names, TTL/lease constraints, protocol checks / network-service owner.'),
('Identity and privileges','Actual native roles match approved duties; tenant cannot modify baseline or foreign resources; recovery path is controlled.','Role and target-scope review, grant/revocation evidence / identity and platform owners.'),
('Certificates and keys','Correct client/issuer/trust relationship, endpoint validation, use versus administration, retained-copy key continuity; no plaintext fallback.','Key/certificate references and observed recovery behaviour / trust custodians.'),
('Logging and monitoring','Events carry usable domain/workload identity; approved collection and time; loss/buffering visible; no broad management access.','Event examples, coverage and alert routing / operations owner.'),
('Storage and protection','Owned attachments/copies, supported capture path, separate transfer/admin, retained catalogue and protected keys; actual isolated restore.','Copy lineage, protection assignment and restore result / storage and backup owners.')],[1.22,3.77,2.15])
b.p('Service reachability is not service entitlement. A shared resolver or repository must not forward tenant traffic or grant administrative rights. For the dedicated service-handoff example, service replies must select the originating tenant context; a convenient default route is not proof of symmetric enforcement.')
b.page(6,titles[5],'Use RB-06 under an explicit non-production test authorization. Candidate capacity can host a restricted disposable fixture to obtain qualification evidence; that permission is not production acceptance.',[('WD',11),('WD',13),('QUAL',5)])
b.table(['Campaign step','What to record','Evidence quality check'],[
('Select scope','Service class, tuple, topology, sharing, families, changed features and requirement assertions.','Select applicable observations; do not make a second qualified stack a prerequisite to the first.'),
('Authorize and prepare','Permitted fault/probe scope, disposable data, time window, restoration and stop authority.','Protect unrelated tenants; no intrusive or destructive test outside this scope.'),
('Build fixture','Two tenants/four domains; approved services and one temporary sequential same-domain probe.','Peak guest fixture demand is accounted for separately from infrastructure overhead.'),
('Prove control paths','Establish healthy endpoints and expected permitted functions before negative observations.','A timeout from a dead endpoint cannot establish a successful isolation result.'),
('Observe outcomes','Capture intended versus realized path, native roles, policy, resource/copy ownership, fault and recovery result.','Distinguish security continuity, availability and actual recovery; no success inferred from tool exit alone.'),
('Review and release','Record passed, failed, blocked, not-run or justified not-applicable; reviewer and immutable artifact references.','Unexecuted or missing mandatory evidence blocks the corresponding qualification.')],[1.23,3.05,2.86])
b.p('The kit carries 80 historical CT procedures, 12 realization addenda and 12 W14 assertions as reference material. They are not 104 executed tests. Applicability must be resolved for the target, and individual assertions may require several observations.')
b.note('Use IT §4 for each test execution and IT §5 for recovery. Include the actual tuple, observation time, topology revision and target identity; never prefill an observed result from an expected result.')
b.page(7,titles[6],'Normal tenant allocation consumes accepted capacity. Production activation has additional prerequisites that a successful infrastructure build cannot waive.',[('RA',23),('WD',9),('IT',7)])
b.table(['Sequence','Execute within accepted scope','Stop / preserve'],[
('1 — Confirm prerequisites','Check G0/G1/G2 for the offered service; confirm current service authority, initial G4 readiness and owner acceptance requirements.','Missing scope or evidence prevents production activation.'),
('2 — Reserve and establish scope','Resolve eligible cell/pools; reserve compute, storage, addresses and edge slots; establish tenant/domain ownership.','No guessed addresses or capacity borrowed from failure reserve.'),
('3 — Denied networks and boundary','Create native networks/gateways and mandatory policies before endpoint connection; configure paired edge routes and flows under their owner.','No fallback public/default route; unverified resources remain isolated.'),
('4 — Resources and services','Use approved images, owned disks and eligible hosts; register names, identities, telemetry and protection.','Do not relax placement or grant broad service-management access to finish a build.'),
('5 — Verify and review','Compare actual placement, attachments, permitted/denied paths, service scope, protection and current evidence.','Unknown, stale or failed mandatory observation keeps the environment restricted.'),
('6 — Controlled activation','Authorized service owner accepts the exact scope; enable only approved exposure and verify the live path.','On failed activation, withdraw exposure while preserving owned data and evidence.'),
('7 — Confirm as-built','Record native identities, actual state, acceptance and support handover.','This confirms already assigned owners; it is not where readiness is first discovered.')],[1.36,3.57,2.21])
b.note('G4 initial readiness precedes G3 production activation. Continuing G4 exercises after activation do not replace the initial proof supporting a promised service. Restricted fixture permission is a separate record.')
b.page(8,titles[7],'Use RB-07. A timeout, lost executor lease or revoked credential does not prove that an accepted native operation stopped.',[('PROV',5),('PROV',6),('WD',10)])
b.table(['Situation','Safe response','Before work resumes'],[
('Unknown native outcome','Freeze competing writes, identify the owning executor, inspect native tasks and actual side effects. Preserve data and logs.','Accountable owner selects resume, supported compensation or forward repair; resource identity is reconciled.'),
('Failed downstream package','Keep incomplete endpoints denied. Release only proven unused reservations; do not delete shared objects or new production data.','Dependent owner accepts the handoff and verifies the changed paths.'),
('Stale plan or changed approval','Reject reuse of a plan whose relevant inputs, policies or state no longer match the approved change.','Re-evaluate differences and obtain the correct scope decision.'),
('Brownfield adoption','Discover actual ownership and dependency before import; review non-destructive changes and remove dual writers deliberately.','A state import is not compliance or permission to replace live disks/gateways.'),
('Emergency containment','Preserve the authorized containment action while reconciling ordinary desired configuration.','Only the designated authority releases the block; record before/after evidence.'),
('Upgrade or capacity expansion','Recheck support tuple, survivor capacity, actual rollback limits and changed assurance paths.','Qualify/canary the changed scope before broad promotion; preserve a recovery path.')],[1.35,3.18,2.61])
b.p('A saved Terraform plan can be reviewed offline using the supplied review_tfplan.py. It reports selected review triggers without inspecting secret-bearing before/after values. It does not evaluate all policy semantics, qualify the provider or approve an apply.')
b.external(['K03','K04','K11'])
b.page(9,titles[8],'Use RB-08 and RB-09. Treat change, recovery and retirement as infrastructure lifecycle operations with data and security consequences.',[('RA',27),('SVC',6),('QUAL',7),('IT',8)])
b.table(['Lifecycle outcome','Required work','Acceptance record'],[
('Operational handover','Confirm support/escalation, actual as-built, telemetry, incident authority, credential custody, capacity limits and maintenance.','Operations accepts a specific service envelope with current evidence, not receipt of generic documentation.'),
('Restore or site recovery','Establish authority and fence ambiguous writers; recover trust/catalogue/keys and foundations; restore isolated data and dependencies.','Measured consistency point and recovery time; useful data and required security verified before reconnection.'),
('Cross-platform migration','Qualify target, transfer state through bounded approved access, verify device/driver/boot/key/data compatibility and final consistency.','Controlled cutover and feasibility of return after new writes; Terraform is not the data conversion engine.'),
('Retirement','Reconcile consumers and holds, create required recovery/export first, withdraw live routes/grants and remove only owned eligible resources.','Remaining copies, keys, owners and disposition are explicit; sanitization receipt before reuse.'),
('Continuing acceptance','Revisit actual service targets, exception expiry, support, resource headroom and periodic recovery after material change.','Current scope accepted or restricted; historical authorization is not rewritten.')],[1.37,3.23,2.54])
b.note('Kit completion means the working records and methods are available. Site completion requires filled values, actual execution evidence, independent review where required and decisions by the designated authorities.')
b.save()

b=Book('IT')
titles=['Change and method-of-procedure cover','Repeatable execution-step record','As-built, deviation and defect record','Test procedure and actual execution record','Recovery exercise and data acceptance','Operational handover and initial readiness','Gate decision and production activation','Migration, retirement and retained data']
b.front('Copy a clean record for each controlled change or test.','The teal fields are editable Word content controls. Use a project-controlled copy, give every execution a stable ID, and retain the final record alongside protected evidence. Add rows or continuation pages as needed; no response field contains a supplied approval.',list(enumerate(titles,1)))
forms=[
('Capture the actual authority and build boundary before executing any change.', [('Change identity','Change ID, purpose, site/service, environment and affected tenants.','IT_CHANGE'),('Controlled inputs','Approved HLD/LLD revisions, package/artifact identifiers and integrity references.','IT_INPUTS'),('Targets and ownership','Exact native resources, current writer/tool, management tuple and exclusions.','IT_TARGETS'),('People and window','Named lead, executors, reviewers, stop authority, escalation and permitted window.','IT_ROLES'),('Readiness and safety','Accepted prerequisites, tested recovery access and approved physical/fault-test safety scope.','IT_READY'),('Approval and conditions','Actual authority-issued change decision, scope, conditions, expiry and evidence reference. Leave unissued until decided.','IT_AUTH')], [('IK',1),('ET',10)]),
('Repeat this page for every independently controlled action; do not bury destructive work inside a generic script step.', [('Step and dependency','Step ID, work package, target, prerequisite receipts and single authoritative executor.','IT_STEP'),('Action and artifact','Exact approved command/configuration or installer procedure, version, parameter source and protected credential reference.','IT_ACTION'),('Expected result','Observable native state, permitted effects, completion signal and maximum wait/retry policy.','IT_EXPECTED'),('Stop and recovery','Conditions to stop, resource state to preserve, data impact, supported rollback or forward-repair action and authority.','IT_STOP'),('Observed execution','Operator, UTC start/end, native task ID, actual output reference and confirmed side effects. No secrets.','IT_OBSERVED'),('Disposition','Completed, failed, blocked or unknown; reviewer, next authorized step and evidence record.','IT_DISPOSITION')], [('IK',2),('IK',8)]),
('Record what exists, not merely what the deployment intended to create.', [('As-built identity','Resource ID/type, owner, tenant/WSD/domain/site, exact release and current authoritative tool.','IT_ASBUILT'),('Observed configuration','Actual interfaces/routes/policy, placement, data attachments, service memberships and configuration digest.','IT_CONFIG'),('Difference from design','Expected design record versus actual state; affected boundaries and dependent resources.','IT_DEVIATION'),('Defect record','Defect ID, observed facts, service/security impact, severity rationale, owner and remediation deadline.','IT_DEFECT'),('Decision and retest','Accepted variation or correction reference, residual risk authority and relevant re-verification.','IT_RETEST'),('Closure','Actual evidence and reviewer; retained issue or confirmed resolution with timestamps.','IT_CLOSE')], [('ET',10),('IK',8)]),
('Expected outcomes and observations are different fields. A not-run test is never a successful test.', [('Test identity and scope','Execution ID, CT/addendum/W14 assertion, requirement, service class, tuple, family, topology and target.','IT_TEST'),('Preconditions and authorization','Healthy permitted control path, endpoint identities, authorized test window, disposable data and restoration safeguards.','IT_PRECONDITIONS'),('Procedure and expected outcome','Approved step sequence, observation points, permitted/denied behaviour and quantitative threshold with source.','IT_TEST_METHOD'),('Actual observations','UTC times, actual native state and endpoint results, logs/trace/configuration artifacts and integrity references.','IT_TEST_OBS'),('Result','Not run / passed / failed / blocked / not applicable. Not applicable needs a scoped reason and approval; never infer pass from timeout.','IT_RESULT'),('Review and impact','Reviewer, discrepancy/defect IDs, applicability decision, evidence freshness and dependent gate.','IT_TEST_REVIEW')], [('IK',6),('WD',13)]),
('Measure the recovery of the defined service, not just a restore job.', [('Recovery scope','Exercise ID, failure scenario, failed/surviving dependencies and approved test authority.','IT_REC_SCOPE'),('Objectives and consistency','Accepted RTO/RPO measurement boundaries, actual last consistent data point, start/end milestones and exclusions.','IT_REC_TARGET'),('Authority and fencing','Who may promote the writer; proof the old writer cannot conflict; key/catalogue/identity custody.','IT_FENCE'),('Restore execution','Actual backup/data set, isolated target, native steps, integrity/application checks and useful recovered-data evidence.','IT_RESTORE'),('Reconnection and failback','Authorized activation, DNS/exposure, reverse transfer or failback feasibility after new writes.','IT_FAILBACK'),('Outcome and improvements','Achieved times/consistency/security, owner acceptance, defects and runbook changes.','IT_REC_RESULT')], [('SVC',6),('IK',9)]),
('Complete the applicable initial readiness before production G3. A later exercise cannot retroactively supply missing initial readiness.', [('Service ownership','Named operations/service/data/security owners, escalation, on-call and supplier support route.','IT_OPS_OWNER'),('As-built and service limits','Accepted topology/configuration, supported versions, capacity/failure envelope, actual SLO/RTO/RPO and exceptions.','IT_SERVICE'),('Monitoring and incidents','Event/health coverage, alert recipients, loss handling, containment and explicit release authority.','IT_MONITORING'),('Trust and protection','Custody references, tested access, keys/catalogue, required restore evidence, holds and retention responsibilities.','IT_CUSTODY'),('Maintenance and continuity','Approved patch/change process, compatible recovery methods, scheduling constraints and runbook location.','IT_MAINT'),('Initial readiness decision','Actual G4 initial authority, scope, reviewed evidence, conditions, validity and signature reference.','IT_G4')], [('IK',7),('QUAL',7)]),
('This is a decision record, not a calculated approval. Check the exact service scope and freshness.', [('Decision requested','Gate ID, service/site/tuple/revision, requested action and accountable authority.','IT_GATE'),('Prerequisite decisions','G0/G1/G2 and applicable G4 initial references; restricted-test permission is not production permission.','IT_PREREQ'),('Evidence and blockers','Current test/restore/ownership records, unresolved findings, accepted exceptions and service restrictions.','IT_GATE_EVIDENCE'),('Operating authority','Separately attributable valid authorization scope/conditions; do not substitute a test report or workbook colour.','IT_OPERATE'),('Actual decision','Not issued / approved / rejected / conditional / suspended; issuer, timestamp, scope and review/expiry.','IT_GATE_DECISION'),('Activation and verification','Permitted exposure change, executor, post-activation observations and safe withdrawal result if needed.','IT_ACTIVATION')], [('DEL',3),('WD',9)]),
('Keep live-service retirement distinct from disposal of all retained data.', [('Lifecycle scope','Change/migration/retirement ID, source/target owners, resources, data classification and dependencies.','IT_LIFE_SCOPE'),('Transfer and cutover','Supported image/data method, bounded paths, final consistency, writer ownership, acceptance and return feasibility.','IT_CUTOVER'),('Retention and copies','Copy/replica/snapshot/backups, holds, owners, locations, necessary keys and remaining authorized access.','IT_COPIES'),('Live cleanup','Withdraw exposures/routes/policies/names/grants, resolve shared resources, quarantine addresses and verify residuals.','IT_LIVE_CLEAN'),('Sanitization and reuse','Approved method, media/key scope, actual verification and receipt; record retained exceptions truthfully.','IT_SANITIZE'),('Final acceptance','Data/operations/security disposition, continuing obligations, retained evidence and final service closure.','IT_LIFE_ACCEPT')], [('IK',9),('WD',12)])]
for n,(lead,rows,refs) in enumerate(forms,1):
 b.page(n,titles[n-1],lead,refs);b.inputs(rows);b.note('Blank fields and unissued decisions are blockers for the affected action. Record actual evidence and authority; examples elsewhere in the library do not populate these fields.')
b.save()

b=Book('EX')
titles=['Trace one decision into engineering and evidence','Resource and boundary schedule','Forward route, return route and service permission','Native realization and provisioning ownership','Commission, qualify, prepare and activate','Capacity and test-resource accounting','Observe, recover and retire without invented results']
b.front('An illustrative completed design chain with deliberately unexecuted acceptance.','This example uses the frozen WD fixture and adds proposed kit record IDs to demonstrate handoffs between teams. It is neither a production design nor a claim that these configurations were built. Real project templates remain blank and separate.',list(enumerate(titles,1)))
b.page(1,titles[0],'Follow the chain from a reasoned architecture selection to a measurable infrastructure result. The same identity appears in the HLD decision, LLD schedule, build step and observation.',[('WD',2),('AK',5),('ET',4),('IT',4)])
b.table(['Layer / example record','Content','Disposition'],[
('Architecture / ADR-EX-01','Use dedicated domain-to-edge handoffs until a shared attachment has proven connected-route, neighbour, source and return-path isolation.','Proposed selection; authority not assigned.'),
('Requirement / ARCH-003, ZIP-001','Independent zone traffic traverses the applicable qualified boundary.','Inherited baseline; target applicability/review required.'),
('Engineering / NET-EX-A01O','D01O native gateway connects to EC-01 through the A01O handoff; forward and reply routes are identified.','Documentation addresses only; native support not established.'),
('Implementation / STEP-EX-01','Owning network/platform executors instantiate the accepted attachment and baseline; edge owner supplies scoped policy.','Not executed; exact site artifact still required.'),
('Verification / OBS-EX-01','W14-01 and relevant CT-003/009/023/024 observations compare actual routes and enforcement with the schedule.','NOT RUN; no observed artifacts.'),
('Acceptance / GATE-EX-01','Relevant G2 qualification and initial G4 readiness precede production G3 and valid operating authority.','NOT ISSUED; example does not grant permission.')],[1.73,3.75,1.66])
b.p('An accepted topology choice would not by itself prove native compatibility. If engineering selects a supported alternative, the changed boundary and evidence must return to the architecture decision owner rather than silently rewriting the intended outcome.')
b.page(2,titles[1],'The example selects one platform for the first campaign. Repeating it on another platform is a separate comparison, not a simultaneous three-platform deployment.',[('WD',3),('WD',4),('WD',5)])
b.table(['Domain / endpoint','Illustrative prefix and gateway','Boundary and owner'],[
('D01O / processor-01','192.0.2.0/27; gateway .1; host .10','Tenant-01; NG-D01O → A01O → EC-01.'),
('D01R / data-01','192.0.2.32/27; gateway .33; host .42','Tenant-01; NG-D01R → A01R → EC-01.'),
('D02O / processor-02','192.0.2.64/27; gateway .65; host .74','Tenant-02; NG-D02O → A02O → EC-02.'),
('D02R / data-02','192.0.2.96/27; gateway .97; host .106','Tenant-02; NG-D02R → A02R → EC-02.'),
('Provider consumption','203.0.113.128/27; SE-01 .129; SE-02 .130','Service endpoints behind security contexts, not a shared native tenant-gateway segment.')],[1.76,2.45,2.93])
b.table(['Link','EC endpoint','Native gateway / service edge'],[
('A01O · 198.51.100.0/30','198.51.100.1','NG-D01O 198.51.100.2'),('A01R · 198.51.100.4/30','198.51.100.5','NG-D01R 198.51.100.6'),('SH-01 · 198.51.100.16/30','EC-01 198.51.100.17','SE-01 198.51.100.18')],[2.70,1.97,2.47])
b.note('All addresses are WD documentation examples. Replace them through authoritative site allocation. These link sizes and logical gateway addresses do not establish native product support or physical port counts.')
b.p('Use EX_Routes4, EX_Routes6 and EX_Flows in the engineering workbook for the full inherited reference schedules. Actual site schedules occupy separate blank working sheets, preventing example values from being mistaken for allocations.')
b.page(3,titles[2],'The following path shows one tenant application service and a shared resolver. Forwarding and policy are distinct.',[('WD',6),('WD',7),('NET',3)])
b.table(['Path segment','Illustrative next-hop decision','Separate policy obligation'],[
('processor-01 → data-01','NG-D01O sends 192.0.2.32/27 toward EC-01 at 198.51.100.1; EC-01 sends toward NG-D01R at .6.','F14-01 permits the selected TCP/443 service with endpoint TLS validation; other services deny.'),
('data-01 → processor-01 reply','NG-D01R sends 192.0.2.0/27 toward EC-01 at .5; EC-01 sends toward NG-D01O at .2.','Stateful replies use the correct context. A new unsolicited reverse connection remains denied.'),
('processor-01 → resolver','Approved resolver 203.0.113.138/32 goes from NG-D01O to EC-01, then SH-01 to SE-01.','Entitled sources may use UDP/53 and TCP/53. No broad provider-subnet permission.'),
('Resolver → tenant-01 reply','The service endpoint sends tenant-01 prefixes through SE-01 .129; SE-01 returns through EC-01 .17.','Correct origin context and source identity; no tenant-02 transit through EC-01.'),
('Management and other services','Not supplied by the application route; published service/admin interfaces remain separate.','No router administration, arbitrary KMS access, repository publication or provider-wide reachability.')],[1.49,3.25,2.40])
b.p('For actual implementation, observe connected routes and the effective forwarding table as well as declared static routes. Required route advertisements, HA next-hop ownership and service endpoint return routing belong in the LLD. A firewall downstream cannot inspect a path that has already bypassed it.')
b.note('No packet has been sent by this worked example. These are intended paths and expected restrictions, not observed results.')
b.page(4,titles[3],'The architecture identifiers remain stable while the selected stack supplies native components and operation semantics.',[('VC',2),('VC',3),('VC',4),('WD',8)])
b.table(['Owner / resource','Nutanix candidate','VMware/NSX or OpenStack candidate'],[
('Platform domain routing','Separate qualified VPC/routing contexts; controlled external attachments.','NSX: independent Tier-1 and supported isolated upstream contexts. OpenStack: separate controlled Neutron routing/network scopes.'),
('Mandatory endpoint policy','Qualified Flow enforcement and protected categories.','NSX: protected group/rule hierarchy. OpenStack: provider-owned effective policy and restricted mutation of ports/groups/attachments.'),
('Compute / storage','Eligible AHV pools and AOS-backed data with explicit sharing and key/copy scope.','Eligible ESXi/datastore or Nova/Placement/Cinder configuration; actual co-residency and supported restore.'),
('Security and services','Edge/service owners instantiate EC/SE and permitted flows; authoritative IPAM/DNS and protection owners supply their functions.','Same architectural responsibility; not assumed to be supplied by the vSphere, NSX or OpenStack provider alone.'),
('Provisioning','Supported native bootstrap plus qualified resource API/provider operations.','Supported installation/lifecycle tools plus scoped Terraform/API ownership; no competing writes to controller-owned backends.')],[1.35,2.44,3.35])
b.p('The actual operation-coverage record must identify observe, create, update, adopt/import, replace, delete and unknown-outcome reconciliation. A candidate mechanism with only create support is not a fully managed service. The selected native commands and resource arguments remain engineering inputs.')
b.note('Exact versions, licenses, hardware, gateway modes and enabled features remain unselected. In particular, verify the NSX parent mode/VRF compatibility recorded in KIT-TN-01 before accepting that candidate design.')
b.page(5,titles[4],'Use the gate dependency rather than assuming that numeric gate order grants chronological permission.',[('WD',9),('DEL',3),('IK',7)])
b.table(['Stage','Example output','Still-required evidence'],[
('G0 / architecture','ADR-EX-01 and selected service scope; tenant/domain/placement and failure constraints.','Actual adopted decision and applicable control responsibilities.'),
('P0–P1 / G1','Restricted recovery access and foundation transport/attachment capacity.','As-built physical and management observations; accepted inventory and actual owners.'),
('P2/P3 installation','Selected native platform, denied boundaries and published provider-service endpoints.','Supported artifacts, native task/configuration receipts and exact tuple.'),
('Restricted P4/P5 fixture','Disposable endpoints and temporary probe; routing, isolation, service and recovery tests.','Specific test authorization; actual observations rather than designed expectations.'),
('G2 / qualification','Accepted service/capability envelope for the first stack.','Applicable passing observations, approved exceptions and measured limits.'),
('G4 initial / readiness','Support, custody, telemetry, incident path and required restore proof ready.','Named owner decisions and evidence supporting the offered service promise.'),
('Production P4/P5 / G3','New authorized tenant instance; current tests, controlled exposure and handover confirmation.','Current prerequisite decisions, valid operating authority and reversible activation record.'),
('P6 / continuing G4','Changes, recovery exercises, migration or retirement.','Current as-built and requalification of materially changed scope.')],[1.68,2.83,2.63])
b.p('STEP-EX-01 cannot be executed from this book alone. The implementation copy must name the approved site LLD, actual resources, tool artifact, executor, credential custody, expected result, stop condition and data-safe recovery step.')
b.page(6,titles[5],'Reference demand and actual deliverable capacity are different quantities. The engineering workbook separates them.',[('WD',11),('QUAL',3),('EK',6)])
b.table(['Reference case','Derived guest demand','Limit of the calculation'],[
('Four permanent endpoints','8 vCPU, 16 GiB memory and 360 GiB virtual disks.','4 × (2 vCPU, 4 GiB, 40 GiB boot), plus two 100 GiB data disks.'),
('One sequential test probe','Peak 10 vCPU, 20 GiB memory and 400 GiB virtual disks.','One extra endpoint at the same small test size; not four simultaneous probes.'),
('Four simultaneous test probes','16 vCPU, 32 GiB memory and 520 GiB virtual disks.','Alternative test execution plan only; cannot count it as the sequential plan.'),
('Provider infrastructure','Additional, not quantified by the four guest VMs.','Controllers, edge/services, protection, replicas, hypervisor overhead and required reserves must be included.'),
('Surviving capacity','Accepted load plus increment must fit each remaining dimension after failure and reserve.','Memory, storage, edge throughput/sessions, routes, attachments and service/API limits cannot substitute for one another.')],[1.73,2.52,2.89])
b.h('MTU example')
b.p('For basic VXLAN carrying an untagged inner Ethernet frame, a 1450-byte workload IP packet adds 14 + 8 + 8 + 20 bytes for inner Ethernet, VXLAN, UDP and outer IPv4: 1500 bytes of outer IP packet. With outer IPv6, use 40 rather than 20: 1520 bytes. An inner VLAN tag adds another 4 bytes. Outer link framing and actual device MTU definitions are separate.')
b.p('The workbook exposes these inputs and arithmetic. Geneve options, IPsec, nested tunnels and other headers need their actual byte budget. An illustrative fit does not establish that every active and surviving path supports the selected workload MTU.')
b.page(7,titles[6],'This example intentionally ends with evidence not supplied and activation not issued. That is the correct result for a documentation kit.',[('IT',4),('IT',5),('IT',8),('WD',13)])
b.table(['Observation / record','Expected outcome','Actual result'],[
('OBS-EX-01 · routing','Approved application and reply paths traverse EC-01; no native bypass.','NOT RUN; no target tuple or observations.'),
('OBS-EX-02 · tenancy','Tenant-01 cannot use tenant-02 paths, data or administrative rights.','NOT RUN; qualified test target required.'),
('OBS-EX-03 · services','Only entitled endpoints; DNS TCP/UDP and fallback operate with correct return scope.','NOT RUN; actual protocol/service configuration required.'),
('OBS-EX-04 · placement','Temporary probe tests within permitted same-domain placements; restart remains eligible.','NOT RUN; approved sharing and host map required.'),
('REC-EX-01 · restore','Useful consistent data, keys/catalogue and isolated target recover within the selected scope.','NOT RUN; no measured RTO/RPO.'),
('RET-EX-01 · retirement','Live grants/routes removed while held copies and recovery keys remain accountable.','NOT RUN; no resource disposal performed.'),
('GATE-EX-01 · activation','Design, qualification, initial readiness and current operating authority all support the delivered scope.','NOT ISSUED; no organization or individual impersonated.')],[2.00,3.20,1.94])
b.p('A completed project would replace these statuses with attributable execution records in IT and the implementation workbook. The historical reference remains unchanged. A supported variation may produce a different native topology while retaining the intended boundaries, resource ownership and service outcomes.')
b.note('Next project action: name the accountable owners and resolve the actual site, platform tuple, boundary mechanism, service parameters and authorization process in the working templates. Those inputs are not invented to make the kit appear production-ready.')
b.save()
