"Generated by scripts/p04/generate_clients.py; identical independent owner/worker recipes."

import re
from typing import Any
from urllib.parse import urlsplit

DEFAULT_QUERIES = {
    "server": ("compute_versions", "compute_flavors", "compute_zones"),
    "network": (
        "network_extensions",
        "network_subnets",
        "network_ports",
        "network_routers",
        "network_security_groups",
        "network_trunks",
        "network_qos",
    ),
    "volume": ("volume_versions", "volume_types"),
}


def configuration_streams(streams: list[dict[str, Any]], platform: str) -> list[dict[str, Any]]:
    result = list(streams)
    if platform != "openstack":
        return result
    present = {s["kind"] for s in streams}
    for stream in streams:
        for query in DEFAULT_QUERIES.get(stream["kind"], ()):
            if "config_" + query in present:
                continue
            base = stream["base_url"]
            if query.endswith("_versions"):
                url = urlsplit(base)
                pattern = r"/v2\.1(?:/[^/]+)?/?$" if stream["kind"] == "server" else r"/v3/[^/]+/?$"
                if not re.search(pattern, url.path):
                    continue
                base = url._replace(path=re.sub(pattern, "", url.path)).geturl()
            result.append(
                {
                    **stream,
                    "kind": "config_" + query,
                    "api_version": "discovery-v1",
                    "base_url": base,
                }
            )
    return result
