import { test, expect } from '@playwright/test';
const base = '/tenants/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/inventory/sites/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/migration-fleet';

test('discovers, groups and prepares source VMs with independent holds and current-group checks', async ({ page, request }, info) => {
  await request.post('/__fleet', { data: { reset: true } });
  const initial = await (await request.get('/__fleet')).json();
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(base);
  await expect(page.getByRole('heading', { name: 'Migrate to OpenStack', exact: true })).toBeFocused();
  await page.getByLabel('Source connection', { exact: true }).selectOption(initial.endpoints.items[0].endpoint_id);
  await page.getByRole('button', { name: 'Refresh from API', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('API discovery queued.');
  await expect(page.locator('img')).toHaveCount(0);
  await page.getByLabel('Find VMs').fill('accounts');
  await page.getByRole('button', { name: 'Select filtered VMs', exact: true }).click();
  await expect(page.getByRole('checkbox', { checked: true })).toHaveCount(2);
  await page.getByLabel('Find VMs').fill('');
  await page.getByLabel('Group list by').selectOption('guest_id');
  await expect(page.getByRole('heading', { name: 'ubuntu64Guest · 2 VMs', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Load more source VMs', exact: true }).click();
  await expect(page.getByText('batch-worker', { exact: true })).toBeVisible();
  await expect(page.getByRole('checkbox', { checked: true })).toHaveCount(2);
  await page.getByLabel('Group name', { exact: true }).fill('Accounts · wave 1');
  await page.getByLabel('OpenStack destination').selectOption(initial.workspace.targets[0].id);
  await page.getByLabel('Catalogue application ID').fill(initial.endpoints.items[0].endpoint_id);
  await page.getByLabel('Catalogue environment ID').fill(initial.endpoints.items[0].endpoint_id);
  await page.getByRole('button', { name: 'Save migration group', exact: true }).click();
  await expect(page).toHaveURL(/\/groups\//);
  await page.getByRole('button', { name: 'Prepare group for OpenStack', exact: true }).click();
  await expect(page.getByText('1 prepared · 1 held', { exact: true })).toBeVisible();
  let state = await (await request.get('/__fleet')).json();
  expect(state.preparations).toHaveLength(2);
  expect(state.preparations[0].revision).toBe(state.group.revision);
  expect(Object.keys(state.preparations[0]).sort()).toEqual(['digest', 'resource_id', 'revision']);
  await page.getByRole('button', { name: 'Find plan choices', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Create selected plans', exact: true })).toBeDisabled();
  await page.getByLabel('Plan for accounts-api', { exact: true }).selectOption(initial.plan_options[0].recipe_id);
  await request.post('/__fleet', { data: { plan_uncertain: true } });
  await page.getByRole('button', { name: 'Create selected plans', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Retry plan creation unchanged', exact: true })).toBeEnabled();
  await expect(page.getByLabel('Plan for accounts-api', { exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Find plan choices', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Retry plan creation unchanged', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Review complete plan', exact: true })).toHaveAttribute('href', new RegExp(`/planning/plans/${initial.plan_id}\\?sites=`));
  state = await (await request.get('/__fleet')).json();
  const composed = state.plan_requests.filter((r: any) => r.operation === 'compose');
  expect(composed).toHaveLength(2); expect(composed[0]).toEqual(composed[1]);
  expect(composed[0].recipe_id).toBe(initial.plan_options[0].recipe_id);
  expect(Object.keys(composed[0]).sort()).toEqual(['base_plan_id', 'command_key', 'digest', 'operation', 'recipe_id', 'resource_id', 'revision']);
  await page.screenshot({ path: info.outputPath('migration-fleet.png'), fullPage: true });
  await page.getByLabel('Group name', { exact: true }).fill('changed');
  await expect(page.getByRole('button', { name: 'Prepare group for OpenStack', exact: true })).toBeDisabled();
  await page.reload();
  await request.post('/__fleet', { data: { stale: true } });
  await page.getByRole('button', { name: 'Prepare group for OpenStack', exact: true }).click();
  await expect(page.getByText('Batch paused. Refresh current findings before preparing again.', { exact: true })).toBeVisible();
  state = await (await request.get('/__fleet')).json(); expect(state.preparations).toHaveLength(3);
  await request.post('/__fleet', { data: { access: 403 } });
  await expect(page).toHaveURL(/\/account$/, { timeout: 25_000 });
  expect(errors).toEqual([]);
});
