import { test, expect } from '@playwright/test';
const route = '/tenants/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/inventory/sites/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/operator-inputs';
test('collects operator inputs, preserves zero and uncertain saves, and remains usable on mobile', async ({ page, request }, info) => {
  await request.post('/__operators', { data: { reset: true } });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.goto(route);
  await expect(page.getByRole('heading', { name: 'Operator readiness', exact: true })).toBeFocused();
  await page.getByLabel('Source platform execution account reference', { exact: true }).fill('vault:site/source-execution');
  await page.getByLabel('Source platform verification account reference', { exact: true }).fill('vault:site/source-verification');
  await page.screenshot({ path: info.outputPath('operator-readiness-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: /Operating targets/ }).click();
  await page.getByLabel('Maximum application outage (seconds)', { exact: true }).fill('0');
  await page.getByLabel('Maximum data loss (bytes)', { exact: true }).fill('0');
  await request.post('/__operators', { data: { uncertain: true } });
  await page.getByRole('button', { name: 'Save operator inputs', exact: true }).click();
  await expect(page.getByRole('alert')).toBeFocused();
  await expect(page.getByRole('button', { name: 'Save operator inputs', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Recover unchanged save' }).click();
  await expect(page.getByRole('status')).toContainText('Operator inputs saved.');
  let state = await (await request.get('/__operators')).json();
  expect(state.posts).toHaveLength(2); expect(state.posts[0]).toEqual(state.posts[1]);
  expect(state.posts[0].input.values.max_outage_seconds).toBe(0);
  expect(state.posts[0].input.values.max_data_loss_bytes).toBe(0);
  const download = await request.get(route + '/download');
  expect((await download.json()).native_write_authorized).toBe(false);
  await expect(page.getByRole('link', { name: 'Download saved packet' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Workspace navigation', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Observed inventory', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close navigation', exact: true }).click();
  expect(await page.locator('body').evaluate(el => el.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('operator-readiness-mobile.png'), fullPage: true });
  await page.getByLabel('Source platform execution account reference', { exact: true }).fill('vault:site/updated');
  await expect(page.getByRole('link', { name: 'Download saved packet' })).toHaveCount(0);
  await request.post('/__operators', { data: { stale: true } });
  await page.getByRole('button', { name: 'Save operator inputs', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('A saved revision');
  await expect(page.getByLabel('Source platform execution account reference', { exact: true })).toHaveValue('vault:site/updated');
  await expect(page.getByRole('button', { name: 'Save operator inputs', exact: true })).toBeDisabled();
  await request.post('/__operators', { data: { access: 403 } });
  await expect(page).toHaveURL(/\/account$/, { timeout: 25_000 });
  expect(errors).toEqual([]);
});
