import { test, expect } from '@playwright/test';
const route = '/tenants/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/inventory/sites/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/operator-inputs';
test('rechecking evidence refreshes the input revision and its matching form values', async ({ page, request }) => {
  const record = { revision: 1, digest: 'a'.repeat(64), values: { source_writer_ref: 'vault:site/original' }, configuration_digest: null, saved_at: Date.now() / 1000 };
  await request.post('/__operators', { data: { reset: true, record } });
  await page.goto(route);
  await expect(page.getByLabel('Source platform execution account reference', { exact: true })).toHaveValue('vault:site/original');
  await request.post('/__operators', { data: { record: { ...record, revision: 2, digest: 'b'.repeat(64), values: { source_writer_ref: 'vault:site/current' } } } });
  await page.getByRole('button', { name: 'Recheck evidence' }).click();
  await expect(page.getByLabel('Source platform execution account reference', { exact: true })).toHaveValue('vault:site/current');
  await expect(page.getByText('Revision 2', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Save operator inputs', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Operator inputs saved.');
  const state = await (await request.get('/__operators')).json();
  expect(state.posts[0].revision).toBe(2);
  expect(state.posts[0].input.values.source_writer_ref).toBe('vault:site/current');
});

test('collects operator inputs, preserves zero and uncertain saves, and remains usable on mobile', async ({ page, request }, info) => {
  await request.post('/__operators', { data: { reset: true } });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.goto(route);
  await expect(page.getByRole('heading', { name: 'Operator readiness', exact: true })).toBeFocused();
  await page.getByLabel('Task', { exact: true }).selectOption('provision');
  await expect(page.getByLabel('Source platform execution account reference', { exact: true })).toHaveCount(0);
  await page.getByLabel('Task', { exact: true }).selectOption('migrate');
  await expect(page.getByLabel('Migration method', { exact: true })).toHaveValue('VM_COLD_EXPORT');
  await page.getByRole('button', { name: /Application recovery and cutover/ }).click();
  await expect(page.locator('#delta_ref')).toHaveCount(0);
  await page.getByLabel('Migration method', { exact: true }).selectOption('VM_SNAPSHOT_BASELINE_APP_DELTA');
  await expect(page.locator('#delta_ref')).toBeVisible();
  await page.getByLabel('Migration method', { exact: true }).selectOption('VM_COLD_EXPORT');
  await page.getByRole('button', { name: /Accounts and trust/ }).click();
  await page.getByLabel('Source platform execution account reference', { exact: true }).fill('vault:site/source-execution');
  await page.getByLabel('Source platform verification account reference', { exact: true }).fill('vault:site/source-verification');
  await page.screenshot({ path: info.outputPath('operator-readiness-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: /Operating targets/ }).click();
  await page.getByLabel('Maximum application outage (seconds)', { exact: true }).fill('0');
  await page.getByLabel('Maximum data loss (bytes)', { exact: true }).fill('0');
  await request.post('/__operators', { data: { uncertain: true } });
  await page.getByRole('button', { name: 'Save operator inputs', exact: true }).click();
  await expect(page.getByRole('alert')).toBeFocused();
  await expect(page.getByRole('button', { name: 'Save operator inputs', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Recover unchanged save' }).click();
  await expect(page.getByRole('status')).toContainText('Operator inputs saved.');
  let state = await (await request.get('/__operators')).json();
  expect(state.posts).toHaveLength(2); expect(state.posts[0]).toEqual(state.posts[1]);
  expect(state.posts[0].input.context).toEqual({ operation: 'migrate', method: 'VM_COLD_EXPORT' });
  expect(state.posts[0].input.values.max_outage_seconds).toBe(0);
  expect(state.posts[0].input.values.max_data_loss_bytes).toBe(0);
  const download = await request.get(route + '/download');
  expect((await download.json()).native_write_authorized).toBe(false);
  await expect(page.getByRole('link', { name: 'Download saved packet' })).toBeVisible();
  await page.getByRole('button', { name: /Operating targets/ }).click();
  await request.post('/__operators', { data: { evidence: { field_id: 'max_outage_seconds', state: 'verified', expires_at: Math.floor(Date.now()/1000) + 3 } } });
  await page.getByRole('button', { name: 'Recheck evidence' }).click();
  await page.getByRole('button', { name: /Operating targets/ }).click();
  await expect(page.getByText('Evidence verified', { exact: true })).toBeVisible();
  await expect(page.getByText('Review expired', { exact: true })).toBeVisible({ timeout: 5000 });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Workspace navigation', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Observed inventory', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close navigation', exact: true }).click();
  expect(await page.locator('body').evaluate(el => el.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('operator-readiness-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: /Accounts and trust/ }).click();
  await page.getByLabel('Source platform execution account reference', { exact: true }).fill('vault:site/updated');
  await expect(page.getByRole('link', { name: 'Download saved packet' })).toHaveCount(0);
  await request.post('/__operators', { data: { stale: true } });
  await page.getByRole('button', { name: 'Save operator inputs', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('A saved revision');
  await expect(page.getByLabel('Source platform execution account reference', { exact: true })).toHaveValue('vault:site/updated');
  await expect(page.getByRole('button', { name: 'Save operator inputs', exact: true })).toBeDisabled();
  await request.post('/__operators', { data: { access: 403 } });
  await expect(page).toHaveURL(/\/account$/, { timeout: 25_000 });
  expect(errors).toEqual([]);
});
