<?php

declare(strict_types=1);

namespace App\Infrastructure\Messaging;

// Generated by scripts/p01/messaging/generate.py; validate the wire schema first.
final readonly class GeneratedEvent
{
    public function __construct(
        public string $event_type,
        public int $schema_version,
        public string $event_id,
        public string $correlation_id,
        public string $tenant_id,
        public string $actor_id,
        public string $record_id,
        public string $revision,
        public string $payload_sha256,
        public string $source_revision,
        public string $occurred_at,
    ) {}
}
