<script setup lang="ts">
import { computed, ref } from 'vue';
import { Link } from '@inertiajs/vue3';
import CatalogueLayout from '../../shared/ui/CatalogueLayout.vue';
import { differences } from '../../features/catalogue/defaults';
import type { Application, Revision, RevisionPage } from '../../features/catalogue/contracts';
const props=defineProps<{tenantId:string;environment:string|null;application:Application;revision:Revision;history:RevisionPage;comparison:Revision|null;canWrite:boolean;notice:string|null}>();
const compare=ref('');const base=computed(()=>`/tenants/${props.tenantId}/applications/${props.application.id}`);const scope=computed(()=>props.environment?'&environment='+props.environment:'');
const changes=computed(()=>props.comparison?differences(props.comparison.intent,props.revision.intent):[]);
</script>
<template>
 <CatalogueLayout :title="application.name" :tenant-id="tenantId">
  <p v-if="notice" role="status" class="mb-4">{{notice}}</p><p class="text-slate-600">Revision {{revision.sequence}} · {{revision.created_at}}</p><p class="mt-2 break-all text-xs">Revision ID {{revision.id}} · SHA-256 {{revision.digest}}</p>
  <Link v-if="canWrite" class="action" :href="`${base}/edit?revision=${revision.id}${scope}`">Revise this intent</Link>
  <Link class="action secondary" :href="`${base}/environments/${revision.intent.environment.id}/planning?revision=${revision.id}`">Compare destinations and plan</Link>
  <div class="mt-7 grid gap-6 lg:grid-cols-3"><section class="space-y-5 lg:col-span-2"><h2 class="text-xl font-semibold">Application intent</h2>
   <dl class="grid gap-2 sm:grid-cols-2"><dt>Service owner</dt><dd class="break-all">{{revision.intent.service_owner_id}}</dd><dt>Environment</dt><dd class="break-all">{{revision.intent.environment.id}} · version {{revision.intent.environment.version}}</dd></dl>
   <h3 class="font-semibold">Acceptance criteria</h3><ul class="list-inside list-disc"><li v-for="criterion in revision.intent.acceptance_criteria" :key="criterion">{{criterion}}</li></ul>
   <article v-for="w in revision.intent.workloads" :key="w.id" class="rounded-xl border border-slate-300 bg-white p-5"><h3 class="text-lg font-semibold">{{w.name}} · {{w.role}}</h3><p>{{w.compute.vcpus}} vCPUs · {{w.compute.memory_mib}} MiB · {{w.guest.os}}</p><dl class="mt-3 text-sm"><dt class="font-semibold">WSD / logical domain</dt><dd class="break-all">{{w.wsd.id}} / {{w.security_domain.id}}</dd><dt class="mt-2 font-semibold">Guest requirements</dt><dd>{{w.guest.firmware}} · secure boot {{w.guest.secure_boot?'required':'not requested'}} · {{w.guest.hardening_profile}}</dd></dl><ul class="mt-3 text-sm"><li v-for="d in w.disks" :key="d.id">Disk {{d.order+1}}: {{d.size_gib}} GiB, {{d.storage_class}}, encryption {{d.encryption}}</li><li v-for="n in w.nics" :key="n.id">Interface {{n.order+1}}: {{n.network_class}}, {{n.address_families.join(' / ')}}, {{n.address_intent}}</li></ul><ul class="mt-3"><li v-for="req in w.requirements" :key="req.key"><strong>{{req.strength}}</strong>: {{req.key}} = {{req.value}} — {{req.reason}}</li></ul></article>
   <h3 class="font-semibold">Dependency direction and readiness</h3><p v-if="!revision.intent.dependencies.length">No dependencies declared.</p><ul class="space-y-2"><li v-for="(edge,index) in revision.intent.dependencies" :key="index" class="rounded border border-slate-200 p-3">{{revision.intent.workloads.find(w=>w.id===edge.from)?.name}} depends on {{revision.intent.workloads.find(w=>w.id===edge.to)?.name}} · {{edge.kind}} · {{edge.strength}}<p>{{edge.readiness}}<span v-if="edge.port"> · {{edge.protocol}}/{{edge.port}}</span><span v-if="edge.controlled_interface"> · controlled interface</span></p></li></ul>
   <h3 class="font-semibold">Data and recovery</h3><ul><li v-for="d in revision.intent.datasets" :key="d.id">{{d.name}} · {{d.consistency}} consistency · RPO {{d.recovery.rpo_seconds}}s / RTO {{d.recovery.rto_seconds}}s · {{d.recovery.method}} ({{d.recovery.strength}})</li></ul>
   <h3 class="font-semibold">Services and application controls</h3><ul><li v-for="s in revision.intent.services" :key="s.name">{{s.name}}: <span v-for="req in s.requirements" :key="req.key">{{req.key}}={{req.value}} ({{req.strength}}); </span></li><li v-for="req in revision.intent.requirements" :key="req.key">{{req.key}}={{req.value}} ({{req.strength}}) — {{req.reason}}</li></ul>
   <details><summary>Complete immutable intent</summary><pre class="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded bg-slate-100 p-4 text-xs">{{JSON.stringify(revision.intent,null,2)}}</pre></details>
  </section><aside class="rounded-xl border border-slate-300 bg-white p-5"><h2 class="text-xl font-semibold">Revision history</h2><ul class="mt-4 space-y-3"><li v-for="item in history.revisions" :key="item.id"><Link :href="`${base}?revision=${item.id}${scope}`" class="text-teal-800 underline">Revision {{item.sequence}}</Link><p class="text-xs">{{item.created_at}}</p></li></ul><Link v-if="history.next_cursor" :href="`${base}?cursor=${encodeURIComponent(history.next_cursor)}${scope}`" class="action secondary">Older revisions</Link><label for="compare-revision" class="mt-6">Compare with<select id="compare-revision" v-model="compare"><option value="">Choose a revision</option><option v-for="item in history.revisions.filter(i=>i.id!==revision.id)" :key="item.id" :value="item.id">Revision {{item.sequence}}</option></select></label><Link v-if="compare" :href="`${base}?revision=${revision.id}&compare=${compare}${scope}`" class="action secondary">Compare revisions</Link></aside></div>
  <section v-if="comparison" class="mt-8"><h2 class="text-xl font-semibold">Revision {{comparison.sequence}} to {{revision.sequence}}</h2><p v-if="!changes.length">The intent is identical.</p><div class="overflow-x-auto"><table v-if="changes.length" class="mt-4 w-full table-fixed"><caption class="sr-only">Immutable intent differences</caption><thead><tr><th scope="col">Field</th><th scope="col">Before</th><th scope="col">After</th></tr></thead><tbody><tr v-for="item in changes" :key="item.path"><th scope="row" class="font-normal">{{item.path}}</th><td>{{item.before}}</td><td>{{item.after}}</td></tr></tbody></table></div></section>
 </CatalogueLayout>
</template>
