<script setup lang="ts">
import { computed } from 'vue';
import { Link, useForm } from '@inertiajs/vue3';
import CatalogueLayout from '../../shared/ui/CatalogueLayout.vue';
import type { Reference, ReferencePage } from '../../features/catalogue/contracts';
const props=defineProps<{tenantId:string;kind:'Environment'|'Wsd'|'SecurityDomain';page:ReferencePage;canWrite:boolean;notice:string|null;actorId:string}>();
const form=useForm({kind:props.kind,command_key:crypto.randomUUID(),reference:null as string|null,etag:null as string|null,retire:false,name:'',owner_id:props.actorId,shareable:false,zone:'OZ'});
const unknown=computed(()=>Object.values(form.errors).some(error=>error.includes('Outcome not confirmed')));
const title=computed(()=>props.kind==='Environment'?'Environments':props.kind==='Wsd'?'Workload security domains':'Logical security domains');
const edit=(r:Reference)=>{form.reference=r.id;form.etag=r.etag;form.name=r.definition.name;form.owner_id=r.definition.owner_id;form.shareable=r.definition.shareable??false;form.zone=r.definition.zone??'OZ';form.command_key=crypto.randomUUID();form.retire=false;document.getElementById('reference-name')?.focus();};
const newId=()=>crypto.randomUUID();
const save=()=>form.post(`/tenants/${props.tenantId}/catalogue-references`,{preserveState:'errors'});
</script>
<template><CatalogueLayout :title="title" :tenant-id="tenantId">
 <nav aria-label="Reference kinds" class="flex flex-wrap gap-5 text-teal-800"><Link v-for="[kind,label] in [['Environment','Environments'],['Wsd','WSDs'],['SecurityDomain','Security domains']]" :key="kind" :href="`/tenants/${tenantId}/catalogue-references?kind=${kind}`" class="underline">{{label}}</Link></nav>
 <p v-if="notice" role="status" class="mt-5">{{notice}}</p><ul class="mt-6 grid gap-4 sm:grid-cols-2"><li v-for="item in page.references" :key="item.id" class="rounded-xl border border-slate-300 bg-white p-5"><h2 class="font-semibold">{{item.definition.name}} · version {{item.version}}</h2><p class="mt-2 break-all text-xs">{{item.id}}</p><p>{{item.retired?'Retired':'Active'}}<span v-if="item.definition.zone"> · {{item.definition.zone}}</span><span v-if="item.definition.shareable !== undefined"> · {{item.definition.shareable?'Same-tenant sharing permitted':'Single-application use'}}</span></p><button v-if="canWrite && !item.retired" type="button" class="secondary" :disabled="unknown" @click="edit(item)">Edit {{item.definition.name}}</button></li></ul>
 <Link v-if="page.next_cursor" :href="`/tenants/${tenantId}/catalogue-references?kind=${kind}&cursor=${encodeURIComponent(page.next_cursor)}`" class="action secondary">Next references</Link>
 <form v-if="canWrite" class="mt-8 max-w-xl space-y-4" @submit.prevent="save"><h2 class="text-xl font-semibold">{{form.reference?'Update reference':'Create reference'}}</h2><p v-if="Object.keys(form.errors).length" role="alert">{{Object.values(form.errors)[0]}}</p><fieldset :disabled="unknown || form.processing"><label for="reference-name">Name<input id="reference-name" v-model="form.name" :readonly="form.reference!==null" required maxlength="200" /></label><label for="reference-owner">Accountable owner ID<input id="reference-owner" v-model="form.owner_id" required /></label><label v-if="kind!=='Environment'"><input v-model="form.shareable" type="checkbox" />Permit sharing between applications in this tenant</label><label v-if="kind==='SecurityDomain'" for="reference-zone">Zone<select id="reference-zone" v-model="form.zone" :disabled="form.reference!==null"><option>PAZ</option><option>OZ</option><option>RZ</option><option>HRZ</option></select></label><p v-if="kind==='SecurityDomain'" class="text-sm">ZIP is a controlled interface, not a workload placement zone.</p><label v-if="form.reference"><input v-model="form.retire" type="checkbox" />Retire this unused reference; retained history stays available</label></fieldset><button :disabled="form.processing" type="submit">{{unknown?'Retry unchanged command':form.retire?'Retire reference':'Save reference'}}</button><button v-if="form.reference" :disabled="unknown || form.processing" type="button" class="secondary ml-3" @click="form.reset();form.command_key=newId()">Create another reference</button></form>
</CatalogueLayout></template>
