#!/usr/bin/env python3
"""Generate Inventory operation descriptors/types; domain decisions remain in their owners."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

def outputs():
    source = ROOT/'contracts/openapi/inventory-v1.3.json'
    api = json.loads(source.read_text())
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    operations = {spec['operationId']: {'method': method.upper(), 'path': path, 'action': spec['x-inventory-action'], 'schema': spec['x-response-schema'], 'status': spec['x-status']} for path, methods in api['paths'].items() for method, spec in methods.items()}
    def php(value):
        if isinstance(value,dict): return '['+', '.join(php(k)+' => '+php(v) for k,v in value.items())+']'
        if isinstance(value,int): return str(value)
        return "'"+value.replace('\\','\\\\').replace("'","\\'")+"'"
    code = "<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Infrastructure\\Inventory;\n\n// Generated by scripts/p04/generate_clients.py; do not edit.\nfinal class GeneratedInventoryOperations\n{\n    public const string SOURCE_SHA256 = '"+digest+"';\n\n    /** @var array<string,array{method:string,path:string,action:string,schema:string,status:int}> */\n    public const array OPERATIONS = "+php(operations)+";\n}\n"
    def ts(s):
        if '$ref' in s:return s['$ref'].split('/')[-1]
        if 'const' in s:return json.dumps(s['const'])
        if 'enum' in s:return ' | '.join(json.dumps(v) for v in s['enum'])
        if 'anyOf' in s:return ' | '.join(ts(v) for v in s['anyOf'])
        if 'oneOf' in s:return ' | '.join(ts(v) for v in s['oneOf'])
        kind=s.get('type')
        if isinstance(kind,list):return ' | '.join(ts({'type':k}) for k in kind)
        if kind=='array':return 'Array<'+ts(s['items'])+'>'
        if kind=='object':
            if 'properties' not in s:return 'Record<string, unknown>'
            return '{ '+'; '.join(json.dumps(k)+('' if k in s.get('required',[]) else '?')+': '+ts(v) for k,v in s['properties'].items())+' }'
        return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}[kind]
    types='// Generated by scripts/p04/generate_clients.py; do not edit.\n'+''.join('export type '+k+' = '+ts(v)+';\n' for k,v in api['components']['schemas'].items())
    outputs = {'apps/console/app/Infrastructure/Inventory/GeneratedInventoryOperations.php':code,'apps/console/resources/contracts/inventory-v1.3.json':source.read_text(),'apps/console/resources/js/features/inventory/contracts.ts':types,'scripts/p04/generated_operations.py':'# Generated; do not edit.\nSOURCE_SHA256 = '+repr(digest)+'\nOPERATIONS = '+repr(operations)+'\n'}
    campaign = ROOT/'contracts/openapi/lifecycle-migration-campaigns-v1.json'
    outputs['apps/console/resources/contracts/lifecycle-migration-campaigns-v1.json'] = campaign.read_text()
    campaign_types = '// Generated by scripts/p04/generate_clients.py; do not edit.\n'+''.join('export type '+k+' = '+ts(v)+';\n' for k,v in json.loads(campaign.read_text())['components']['schemas'].items())
    outputs['apps/console/resources/js/features/jobs/campaigns.ts'] = campaign_types
    expansion = '"Generated by scripts/p04/generate_clients.py; identical independent owner/worker recipes."\n\nimport re\nfrom typing import Any\nfrom urllib.parse import urlsplit\n\nDEFAULT_QUERIES = {\n    "server": ("compute_versions", "compute_flavors", "compute_zones"),\n    "network": (\n        "network_extensions",\n        "network_subnets",\n        "network_ports",\n        "network_routers",\n        "network_security_groups",\n        "network_trunks",\n        "network_qos",\n    ),\n    "volume": ("volume_versions", "volume_types"),\n}\n\n\ndef configuration_streams(streams: list[dict[str, Any]], platform: str) -> list[dict[str, Any]]:\n    result = list(streams)\n    if platform != "openstack":\n        return result\n    present = {s["kind"] for s in streams}\n    for stream in streams:\n        for query in DEFAULT_QUERIES.get(stream["kind"], ()):\n            if "config_" + query in present:\n                continue\n            base = stream["base_url"]\n            if query.endswith("_versions"):\n                url = urlsplit(base)\n                pattern = r"/v2\\.1(?:/[^/]+)?/?$" if stream["kind"] == "server" else r"/v3/[^/]+/?$"\n                if not re.search(pattern, url.path):\n                    continue\n                base = url._replace(path=re.sub(pattern, "", url.path)).geturl()\n            result.append(\n                {\n                    **stream,\n                    "kind": "config_" + query,\n                    "api_version": "discovery-v1",\n                    "base_url": base,\n                }\n            )\n    return result\n'
    for package in ('services/inventory/src/inventory', 'workers/inventory/src/inventory_worker'):
        outputs[package + '/infrastructure/generated_configuration_streams.py'] = expansion
    return outputs

def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    for name,value in outputs().items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_text()!=value:raise SystemExit('Stale generated output: '+name)
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(value)
    print('Inventory PHP/Python operation descriptors and Vue types match the versioned contract.')

if __name__=='__main__':main()
