#!/usr/bin/env python3
"""Generate deterministic operation descriptors and Vue intent types from Catalogue v1.

This small generator owns no domain behavior. Runtime validation remains the owner's
schema and consumer adapters. It does not claim general OpenAPI code generation.
"""
from pathlib import Path
import argparse,hashlib,json
ROOT=Path(__file__).resolve().parents[2]
def outputs():
 source=ROOT/'contracts/openapi/catalogue-v1.0.1.json';api=json.loads(source.read_text());digest=hashlib.sha256(source.read_bytes()).hexdigest()
 operations={spec['operationId']:{'method':method.upper(),'path':path,'action':spec['x-catalogue-action'],'schema':spec['x-response-schema'],'status':200 if method=='get' else 201} for path,methods in api['paths'].items() for method,spec in methods.items()}
 def php(v):
  if isinstance(v,dict):return '['+', '.join(php(k)+' => '+php(x) for k,x in v.items())+']'
  if isinstance(v,int):return str(v)
  return "'"+v.replace('\\','\\\\').replace("'","\\'")+"'"
 code="<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Infrastructure\\Catalogue;\n\n// Generated by scripts/p03/generate_clients.py; do not edit.\nfinal class GeneratedCatalogueOperations\n{\n    public const string SOURCE_SHA256 = '"+digest+"';\n\n    /** @var array<string,array{method:string,path:string,action:string,schema:string,status:int}> */\n    public const array OPERATIONS = "+php(operations)+";\n}\n"
 def ts(schema):
  if '$ref' in schema:return schema['$ref'].split('/')[-1]
  if 'const' in schema:return json.dumps(schema['const'])
  if 'enum' in schema:return ' | '.join(json.dumps(x) for x in schema['enum'])
  if 'anyOf' in schema:return ' | '.join(ts(x) for x in schema['anyOf'])
  t=schema.get('type')
  if isinstance(t,list):return ' | '.join(ts(schema|{'type':x}) for x in t)
  if t=='object':return '{ '+ '; '.join(json.dumps(k)+('' if k in schema.get('required',[]) else '?')+': '+ts(v) for k,v in schema['properties'].items())+' }'
  if t=='array':return 'Array<'+ts(schema['items'])+'>'
  return {'integer':'number','number':'number','string':'string','boolean':'boolean','null':'null'}[t]
 types='// Generated by scripts/p03/generate_clients.py; do not edit.\n'+''.join('export type '+name+' = '+ts(schema)+';\n' for name,schema in api['components']['schemas'].items())
 python='# Generated by scripts/p03/generate_clients.py; do not edit.\nSOURCE_SHA256 = '+repr(digest)+'\nOPERATIONS = '+repr(operations)+'\n'
 return {'apps/console/app/Infrastructure/Catalogue/GeneratedCatalogueOperations.php':code,'apps/console/resources/contracts/catalogue-v1.json':source.read_text(),'apps/console/resources/js/features/catalogue/contracts.ts':types,'scripts/p03/generated_operations.py':python}
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
 for name,value in outputs().items():
  path=ROOT/name
  if a.check:
   if not path.exists() or path.read_text()!=value:raise SystemExit('Generated contract output is stale: '+name)
  else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(value)
 print('Catalogue PHP operation client, Python operation descriptors and Vue types are current.')
if __name__=='__main__':main()
