"""Actual bounded Nova/Cinder/Neutron plus VM-referenced Glance GETs for one attested project campaign.

No Keystone login, catalog discovery, token refresh, mutation, server-link follow
or authentication fallback exists. The credential custodian signs all four
native endpoints and the token's project scope; RBAC remains independently checked.
"""
from __future__ import annotations

from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from threading import RLock
from typing import Callable, Mapping
from urllib.parse import urlencode, urlsplit

from .openstack import (OpenStackHTTPError, OpenStackServiceEndpoints,
    _COLLECTIONS, _CORE_SERVICES, _REQUIRED_KINDS, _SERVICES, _image, _next_link, _object, _quota,
    collect_openstack_project)
from .openstack_credentials import API_VERSIONS, COLLECTOR_ID, SignedFileOpenStackCredentialSource
from ..model import DiscoveryCampaignAuthorization, _id, _utc
from ..native_credentials import NativeReadHeld
from ..native_https import read_json
from ..read_budget import NativeReadGate, NativeReadAdmissionHeld
from ..trust import BoundDiscoveryIngestVerifier


class OpenStackHttpsTransport:
    """Serial, one-use collection with exact service routes and bounded cursors.

    Only canonical next requests generated by the existing project collector are
    accepted. A failed attempt latches this instance closed, including HTTP errors
    and post-response authorization failure. Re-admission/restart custody remains
    the site runtime's responsibility, not an in-memory replay guarantee.
    """
    def __init__(self, campaign: DiscoveryCampaignAuthorization, endpoints: OpenStackServiceEndpoints,
                 environment_id: str, *, verifier: BoundDiscoveryIngestVerifier,
                 credentials: SignedFileOpenStackCredentialSource,
                 ca_bundles: Mapping[str, str | Path], timeout: float = 5.0,
                 max_response_bytes: int = 4 * 1024 * 1024,
                 clock: Callable[[], datetime] = lambda: datetime.now(timezone.utc),
                 read_gate: NativeReadGate | None = None):
        if (not isinstance(campaign, DiscoveryCampaignAuthorization)
                or campaign.scope.platform_family != 'openstack'
                or campaign.collector_id != COLLECTOR_ID or set(campaign.allowed_kinds) != _REQUIRED_KINDS
                or not isinstance(endpoints, OpenStackServiceEndpoints)
                or endpoints.endpoint_id != campaign.scope.endpoint_id
                or endpoints.project_id != campaign.scope.native_scope_id
                or not _id(environment_id) or not isinstance(verifier, BoundDiscoveryIngestVerifier)
                or not isinstance(credentials, SignedFileOpenStackCredentialSource)
                or not isinstance(ca_bundles, Mapping) or set(ca_bundles) != set(_SERVICES)
                or type(timeout) not in (int, float) or not 0 < timeout <= 15
                or type(max_response_bytes) is not int or not 1024 <= max_response_bytes <= 4*1024*1024
                or not callable(clock)):
            raise ValueError('Exact OpenStack campaign and bounded native read configuration required')
        self._campaign, self._endpoints, self._environment = campaign, endpoints, environment_id
        self._verifier, self._credentials = verifier, credentials
        self._ca = {service: Path(ca_bundles[service]) for service in _SERVICES}
        if read_gate is not None:
            if not isinstance(read_gate, NativeReadGate):
                raise TypeError('A native endpoint read gate is required')
            read_gate.require_scope(campaign.scope)
        self._read_gate = read_gate
        self._admission_failed = False
        self._timeout, self._max_bytes, self._clock = timeout, max_response_bytes, clock
        self._last_time, self._lock = campaign.issued_at, RLock()
        self._requests = self._stage = self._objects = 0
        self._marker = None
        self._seen: set[tuple[str, str]] = set()
        self._image_ids: set[str] = set()
        self._failed = self._finished = False

    @property
    def bound_scope(self):
        return self._campaign.scope

    @property
    def authenticated_project_id(self):
        # This selection is checked against independently signed token material
        # and native RBAC witnesses before every network operation.
        return self._endpoints.project_id

    def _now(self):
        if self._read_gate is not None:
            self._read_gate.check()
        if self._admission_failed:
            raise NativeReadAdmissionHeld('Native read admission did not complete')
        now = self._clock()
        if not _utc(now) or not self._last_time <= now < self._campaign.expires_at:
            raise NativeReadHeld('Native read campaign expired or clock regressed')
        self._last_time = now
        return now

    def _authorize(self):
        now = self._now()
        material = self._credentials.read(self._campaign, self._endpoints, self._environment, checked_at=now)
        self._verifier.verify_read_credential(self._campaign, self._environment, now,
            material.credential_reference, self._credentials.authority_public_key)
        self._now()
        return material

    def collect(self):
        if not self._lock.acquire(timeout=self._timeout):
            raise NativeReadHeld('Native discovery collection is already active')
        try:
            if self._requests or self._failed or self._finished:
                raise NativeReadHeld('Native discovery collection is not reusable')
            self._authorize()
            pages = collect_openstack_project(self._campaign, self._endpoints, self, clock=self._now)
            self._authorize()
            # The pure collector may turn an I/O error into a diagnostic page.
            # This native client must not release a failed/revoked or short scan.
            if self._failed or self._stage != 6 + len(self._image_ids):
                raise NativeReadHeld('Native project collection did not finish its exact read set')
            last = pages[-1]
            return (*pages[:-1], replace(last, terminal_completeness='PARTIAL',
                collection_errors=(*last.collection_errors, 'VISIBLE_INVENTORY_ONLY')))
        except Exception as exc:
            self._admission_failed |= isinstance(exc, NativeReadAdmissionHeld)
            self._failed = True
            raise NativeReadHeld('Verified OpenStack campaign collection unavailable') from None
        finally:
            self._finished = True
            self._lock.release()

    def get_json(self, endpoint: str, path: str, params: Mapping[str, str]) -> Mapping[str, object]:
        if not self._lock.acquire(timeout=self._timeout):
            raise NativeReadHeld('Native discovery read is already active')
        try:
            if self._failed or self._finished or self._requests >= self._campaign.max_pages:
                raise NativeReadHeld('Native read budget or sequence is exhausted')
            service = (_CORE_SERVICES[self._stage % 3] if self._stage < 6 else 'image')
            if self._stage < 3:
                _, expected_path, list_key, links_key, kind = _COLLECTIONS[self._stage]
                expected_params = {'limit': str(self._campaign.max_page_size)}
                if service == 'compute':
                    expected_params['all_tenants'] = 'false'
                if self._marker is not None:
                    expected_params['marker'] = self._marker
            elif self._stage < 6:
                expected_path = (f'quotas/{self._endpoints.project_id}' if service == 'network'
                                 else f'os-quota-sets/{self._endpoints.project_id}')
                expected_params = {}
            else:
                images = sorted(self._image_ids)
                offset = self._stage - 6
                if offset >= len(images):
                    raise NativeReadHeld('Native image read sequence is exhausted')
                expected_path = f'images/{images[offset]}'
                expected_params = {}
            if (endpoint != self._endpoints.for_service(service) or path != expected_path
                    or not isinstance(params, Mapping) or dict(params) != expected_params):
                raise NativeReadHeld('Native request differs from the admitted next project read')
            query = dict(expected_params)
            if self._stage == 2:
                query['project_id'] = self._endpoints.project_id
            self._requests += 1
            material = self._authorize()
            selected = material.for_service(service)
            url = urlsplit(selected.url)
            headers = ({'OpenStack-API-Version': service + ' ' + API_VERSIONS[service]}
                       if service in ('compute', 'volume') else {})

            def current():
                if self._authorize().binding_digest != material.binding_digest:
                    raise NativeReadHeld('Native credential rotated during read')

            status, value = read_json(origin=f'{url.scheme}://{url.netloc}', connect_ip=selected.connect_ip,
                ca_digest=selected.ca_digest, ca_bundle=self._ca[service],
                path=url.path + '/' + expected_path + ('?' + urlencode(query) if query else ''),
                credential_header='X-Auth-Token', credential=material.token,
                timeout=min(self._timeout, (self._campaign.expires_at - self._now()).total_seconds()),
                max_response_bytes=self._max_bytes, authorize=current, read_gate=self._read_gate,
                request_headers=headers, response_headers=headers)
            if status != 200:
                if 400 <= status <= 599:
                    raise OpenStackHTTPError(status)
                raise NativeReadHeld('Unexpected native HTTP status')
            if not isinstance(value, dict):
                raise NativeReadHeld('Native project response is not a JSON object')
            if self._stage < 3:
                rows = value.get(list_key)
                if not isinstance(rows, list) or len(rows) > self._campaign.max_page_size:
                    raise NativeReadHeld('Native collection exceeds its page bound')
                identities = []
                for row in rows:
                    if not isinstance(row, dict):
                        raise NativeReadHeld('Native collection row is not an object')
                    # Reuse the provider's actual parser, including ownership
                    # checks, before deriving an admitted next marker.
                    parsed = _object(self.bound_scope, kind, row)
                    identity = parsed.identity.native_id
                    if kind == 'vm':
                        image_fact = next(fact for fact in parsed.facts if fact.name == 'imageId')
                        if image_fact.state == 'KNOWN' and image_fact.value() is not None:
                            self._image_ids.add(image_fact.value())
                    if (service, identity) in self._seen:
                        raise NativeReadHeld('Native identity repeated across pages')
                    self._seen.add((service, identity))
                    identities.append(identity)
                self._objects += len(identities)
                last_id = identities[-1] if identities else None
                linked = _next_link(value, links_key, endpoint, expected_path, last_id)
                if linked or len(rows) == self._campaign.max_page_size:
                    if not last_id or last_id == self._marker:
                        raise NativeReadHeld('Native pagination did not advance')
                    self._marker = last_id
                else:
                    self._stage += 1
                    self._marker = None
            elif self._stage < 6:
                _quota(self.bound_scope, service, value)
                self._objects += 1
                self._stage += 1
            else:
                expected_image = expected_path.removeprefix('images/')
                parsed = _image(self.bound_scope, value)
                if parsed.identity.native_id != expected_image:
                    raise NativeReadHeld('Native image response differs from its VM reference')
                if ('image', expected_image) in self._seen:
                    raise NativeReadHeld('Native image identity repeated')
                self._seen.add(('image', expected_image))
                self._objects += 1
                self._stage += 1
            if self._objects > self._campaign.max_objects:
                raise NativeReadHeld('Native object budget exceeded')
            current()
            return value
        except OpenStackHTTPError:
            self._failed = True
            raise
        except Exception as exc:
            self._admission_failed |= isinstance(exc, NativeReadAdmissionHeld)
            self._failed = True
            raise NativeReadHeld('Verified OpenStack HTTPS read unavailable') from None
        finally:
            self._lock.release()
