"""Generate private scalar envelope DTOs and copy the authoritative schema."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]

def outputs():
    schema_path = ROOT / "contracts/schemas/events/catalogue-foundation-recorded-v1.json"
    schema = json.loads(schema_path.read_text())
    props = schema["properties"]
    if schema["required"] != list(props) or any(p["type"] not in ("string", "integer") for p in props.values()):
        raise ValueError("Generator supports required scalar envelope DTOs only")
    php = "<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Infrastructure\\Messaging;\n\n// Generated by scripts/p01/messaging/generate.py; validate the wire schema first.\nfinal readonly class GeneratedEvent\n{\n    public function __construct(\n"
    php += "".join("        public "+("int" if p["type"] == "integer" else "string")+" $"+n+",\n" for n,p in props.items())
    php += "    ) {}\n}\n"
    py = '\n'.join(['"""Generated scalar DTO; validate the wire schema before constructing."""', '', 'from dataclasses import dataclass', '', '', '@dataclass(frozen=True)', 'class GeneratedEvent:', *['    '+n+': '+('int' if p['type']=='integer' else 'str') for n,p in props.items()], ''])
    return {
        'services/catalogue/app/Infrastructure/Messaging/GeneratedEvent.php':php,
        'services/planning/src/planning/infrastructure/messaging/generated.py':py,
        'services/catalogue/resources/contracts/foundation-event.json':schema_path.read_text(),
        'services/planning/src/planning/infrastructure/messaging/foundation-event.json':schema_path.read_text(),
    }

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,content in outputs().items():
        path=ROOT/name
        if args.check:
            if not path.is_file() or path.read_text()!=content: raise SystemExit('Generated contract drift: '+name)
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
