#!/usr/bin/env python3
"""Build typed WSD compositions from the reviewed native component interfaces."""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMPONENTS = {
    'nutanix': {'domains': 'nutanix-domain', 'workloads': 'nutanix-workload'},
    'vmware': {'domains': 'nsx-domain', 'workloads': 'vsphere-workload'},
    'openstack': {'domains': 'openstack-domain', 'workloads': 'openstack-workload'},
}


def rendered(root=ROOT):
    files, entries = {}, []
    for platform, phases in COMPONENTS.items():
        for phase, component in phases.items():
            primitive = root / 'terraform/modules' / component
            old_root = root / 'terraform/stacks/components' / component
            native = json.loads((primitive / 'main.tf.json').read_text(encoding='utf-8'))
            config = json.loads((old_root / 'main.tf.json').read_text(encoding='utf-8'))
            common = {'tenant_key', 'allow_restricted_build', 'test_authorization_ref'}
            identity = 'domain_key' if phase == 'domains' else 'workload_key'
            attrs = {k: v for k, v in native['variable'].items() if k not in common | {identity}}
            fields = ', '.join(k + ' = ' + (f"optional({v['type']}, {json.dumps(v['default'])})"
                                           if 'default' in v else v['type']) for k, v in attrs.items())
            variables = {k: copy.deepcopy(v) for k, v in native['variable'].items() if k in common}
            variables['wsd_key'] = {
                'type': 'string', 'nullable': False,
                'validation': [{'condition': '${can(regex("^[a-z][a-z0-9-]{1,40}$", var.wsd_key))}',
                                'error_message': 'A stable WSD identity is required.'}],
            }
            for key in ('environment_key', 'site_key'):
                variables[key] = copy.deepcopy(variables['wsd_key'])
                variables[key]['validation'][0]['condition'] = variables[key]['validation'][0]['condition'].replace('var.wsd_key', 'var.' + key)
                variables[key]['validation'][0]['error_message'] = 'A stable environment/site identity is required.'
            variables['members'] = {
                'type': 'map(object({' + fields + '}))', 'nullable': False,
                'description': f'{phase} owned by this tenant/WSD; map keys are immutable native identities.',
                'validation': [{'condition': '${length(var.members) > 0}',
                                'error_message': 'An empty WSD scope is not an allocation or retirement request.'}],
            }
            # Retain primitive validation in each child. Map keys are stable Terraform addresses.
            child = {'source': f'../../../modules/{component}', 'for_each': '${var.members}'}
            child.update({k: '${var.' + k + '}' for k in sorted(common)})
            child[identity] = '${each.key}'
            child.update({k: '${each.value.' + k + '}' for k in attrs})
            scope = {'tenant_key': '${var.tenant_key}', 'wsd_key': '${var.wsd_key}',
                     'platform': platform, 'phase': phase,
                     'environment_key': '${var.environment_key}', 'site_key': '${var.site_key}'}
            module = {
                '//': 'Generated by scripts/build_wsd_compositions.py; restricted native composition.',
                'terraform': copy.deepcopy(native['terraform']), 'variable': variables,
                'module': {'member': child},
                'output': {'scope': {'value': scope}, 'members': {'value': '${module.member}'},
                           'delivery_state': {'value': 'PREPARED_NOT_QUALIFIED_NOT_SERVICE_READY'}},
            }
            module_path = f'terraform/compositions/{platform}/{phase}'
            root_path = f'terraform/stacks/wsd/{platform}/{phase}'
            credentials = {k: v for k, v in config['variable'].items() if k not in native['variable']}
            stack = {
                '//': module['//'], 'terraform': copy.deepcopy(config['terraform']),
                'provider': config['provider'], 'variable': {**variables, **credentials},
                'module': {'owned': {'source': f'../../../../compositions/{platform}/{phase}',
                                     **{k: '${var.' + k + '}' for k in variables}}},
                'output': {k: {'value': '${module.owned.' + k + '}'} for k in module['output']},
            }
            files[module_path + '/main.tf.json'] = json.dumps(module, indent=2) + '\n'
            files[root_path + '/main.tf.json'] = json.dumps(stack, indent=2) + '\n'
            lock = (primitive / '.terraform.lock.hcl').read_text(encoding='utf-8')
            files[module_path + '/.terraform.lock.hcl'] = lock
            files[root_path + '/.terraform.lock.hcl'] = lock
            example = json.loads((old_root / 'inputs.tfvars.json.example').read_text(encoding='utf-8'))
            member = {k: example[k] for k in attrs if k in example}
            inputs = {k: example[k] for k in sorted(common)}
            inputs.update(wsd_key='wsd-01', environment_key='qualification-01', site_key='site-01', members={example[identity]: member})
            files[root_path + '/inputs.tfvars.json.example'] = json.dumps(
                {**inputs, **{k: example[k] for k in credentials if k in example}}, indent=2) + '\n'
            inputs['allow_restricted_build'] = True
            inputs['test_authorization_ref'] = 'MOCK-ONLY-NO-REAL-AUTHORITY'
            if phase == 'workloads':
                member['accepted_quarantine_ref'] = 'MOCK-ONLY-NOT-ACCEPTED'
            mocks = '\n'.join('mock_provider "' + k + '" {}' for k in native['terraform']['required_providers'])
            values = '\n'.join('  ' + k + ' = ' + json.dumps(v) for k, v in inputs.items())
            # Plan a real child graph with mocked provider calls, then prove an empty scope rejects.
            test = mocks + '\n\nvariables {\n' + values + '\n}\n\n'
            test += '''run "restricted_composition" {
  command = plan
  assert {
    condition = length(output.members) == 1 && output.scope.wsd_key == "wsd-01"
    error_message = "Stable owned members and WSD identity must be published."
  }
  assert {
    condition = output.delivery_state == "PREPARED_NOT_QUALIFIED_NOT_SERVICE_READY"
    error_message = "Preparation must never imply activation."
  }
}

run "empty_scope_rejected" {
  command = plan
  variables { members = {} }
  expect_failures = [var.members]
}
'''
            files[module_path + '/tests/composition.tftest.hcl'] = test
            entries.append({'id': f'{platform}-wsd-{phase}', 'platform': platform, 'kind': 'composition',
                            'module': module_path, 'root': root_path, 'owner_scope': 'wsd'})
    catalog = json.loads((root / 'terraform/catalog.json').read_text(encoding='utf-8'))
    catalog['entries'] = [e for e in catalog['entries'] if e['kind'] == 'component'] + entries
    files['terraform/catalog.json'] = json.dumps(catalog, indent=2) + '\n'
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = []
    for name, content in rendered().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            changed.append(name)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    print(json.dumps({'changed': changed, 'check_only': args.check}))
    return bool(changed) if args.check else 0


if __name__ == '__main__':
    raise SystemExit(main())
