#!/usr/bin/env python3
"""Generate private data projections; definitions never confer qualified support."""

import argparse
import ast
import hashlib
import json
from pathlib import Path
from pprint import pformat

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'contracts/capabilities/definitions-v1.json'
PYTHON = {
    'services/planning': 'planning',
    'services/inventory': 'inventory',
    'services/lifecycle': 'lifecycle',
    'workers/inventory': 'inventory_worker',
    'workers/lifecycle': 'lifecycle_worker',
}


def projections(data):
    if data['schema_version'] != 1 or data['definition_version'] != '1.0.0':
        raise ValueError('Unsupported definition version; add a new version explicitly')
    from jsonschema import Draft202012Validator

    schema = json.loads((ROOT / 'contracts/schemas/capabilities/definitions-v1.json').read_text())
    Draft202012Validator(schema).validate(data)
    methods = data['methods']
    aliases = {v['v1_alias']: k for k, v in methods.items()}
    if len(aliases) != len(methods) or not all(v['implementation_required'] is True for v in methods.values()):
        raise ValueError('Methods require distinct aliases and native implementations')
    stages = {}
    for method, row in methods.items():
        if set(row['stages']) != set(data['modes']):
            raise ValueError('Missing method mode')
        implementation = row['implementation']
        handler = ROOT / implementation['handler']
        conformance = ROOT / implementation['conformance']
        if not handler.is_file() or not conformance.is_file():
            raise ValueError('Unimplemented capability method: ' + method)
        literals = {node.value for node in ast.walk(ast.parse(handler.read_text())) if isinstance(node, ast.Constant) and isinstance(node.value, str)}
        if row['v1_alias'] not in literals:
            raise ValueError('Handler does not implement method: ' + method)
        for mode, order in row['stages'].items():
            if not order or len(order) != len(set(order)) or any(s not in data['stage_before'] or s not in data['stage_after'] for s in order):
                raise ValueError('Missing or duplicate stages/cases')
            stages[(mode, row['v1_alias'])] = tuple(order)
    canonical = json.dumps(data, sort_keys=True, ensure_ascii=True, separators=(',', ':'))
    checksum = hashlib.sha256(canonical.encode()).hexdigest()
    text = '"""Generated by scripts/generate_capabilities.py; declarations grant no support."""\n\n'
    text += 'from collections.abc import Mapping\nfrom types import MappingProxyType\n\n'
    text += f'DEFINITION_VERSION = {data["definition_version"]!r}\nDEFINITION_SHA256 = {checksum!r}\n'
    for name in ('platforms', 'dimensions', 'actions', 'strategies', 'guests', 'operations', 'retest_triggers', 'modes'):
        text += f'{name.upper()} = {tuple(data[name])!r}\n'
    text += f'METHODS = {tuple(methods)!r}\nLEGACY_METHODS = {tuple(aliases)!r}\n'
    text += f'RECOVERY_MODES = {tuple(k for k in data["modes"] if k not in {"rehearsal", "cutover"})!r}\n'
    tables = {
        'METHOD_ALIASES': ('str, str', aliases),
        'METHOD_DELTA': ('str, str', {v['v1_alias']: v['delta'] for v in methods.values()}),
        'STAGES': ('tuple[str, str], tuple[str, ...]', stages),
        'BEFORE': ('str, tuple[str, ...]', {k: tuple(v) for k, v in data['stage_before'].items()}),
        'AFTER': ('str, tuple[str, ...]', {k: tuple(v) for k, v in data['stage_after'].items()}),
        'TERMINALS': ('str, str', data['terminals']),
        'MATCHERS': ('str, tuple[str, str | None]', {k: (v['comparison'], v['unit']) for k, v in data['requirements'].items()}),
    }
    for name, (annotation, table) in tables.items():
        text += f'{name}: Mapping[{annotation}] = MappingProxyType(\n{pformat(table, width=88, sort_dicts=False)}\n)\n'
    # Use the locked product formatter to produce checked-in source, not a network formatter.
    import subprocess

    formatter = ROOT / 'services/planning/.venv/bin/ruff'
    text = subprocess.check_output([str(formatter), 'format', '--stdin-filename', 'capability_definitions.py'], input=text, text=True)
    output = {ROOT / f'{root}/src/{package}/domain/capability_definitions.py': text for root, package in PYTHON.items()}
    php = "<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Domain\\Qualification;\n\n"
    php += '/** Generated definition metadata; Assurance decisions remain independent. */\nfinal class CapabilityDefinitions\n{\n'
    php += f"    public const string SHA256 = '{checksum}';\n\n"
    php += f"    public const string VERSION = '{data['definition_version']}';\n\n"
    for name, value in [('PLATFORMS', data['platforms']), ('METHODS', list(methods)), ('LEGACY_METHODS', list(aliases))]:
        php += f"    public const array {name} = [" + ', '.join(repr(v) for v in value) + '];\n\n'
    php = php.rstrip() + '\n}\n'
    output[ROOT / 'services/assurance/app/Domain/Qualification/CapabilityDefinitions.php'] = php
    ts = '// Generated capability metadata. Qualification and admission remain owner decisions.\n'
    ts += 'export const capabilityDefinitions = ' + json.dumps({'sha256': checksum, **data}, indent=4) + ' as const;\n'
    output[ROOT / 'apps/console/resources/js/features/planning/capabilityDefinitions.ts'] = ts
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in projections(json.loads(SOURCE.read_text())).items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit('Capability definition drift: ' + str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print('Capability definitions and seven private projections agree')


if __name__ == '__main__':
    main()
