import { test, expect } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import type { Intent } from '../../resources/js/features/catalogue/contracts';

test('authors complete intent, preserves conflicts and uncertain retries, compares history and clears revoked access', async ({ browser, request }) => {
  const fixture = JSON.parse(readFileSync(process.env.P03_BROWSER_FIXTURE!, 'utf8'));
  const context = await browser.newContext({ baseURL: process.env.CONSOLE_BASE_URL });
  await context.addCookies([fixture.author_cookie]);
  const page = await context.newPage();
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => { void dialog.accept(); });
  const base = `/tenants/${fixture.tenant}/applications`;
  await page.goto(`${base}/create`);
  await expect(page.getByRole('heading', { name: 'Create application', exact: true })).toBeVisible();
  await page.getByLabel('Application name', { exact: true }).fill('Browser Permit Desk');
  await page.getByRole('button', { name: 'Import complete intent', exact: true }).click();
  const invalid: Intent = structuredClone(fixture.intent);
  invalid.workloads[0]!.nics[0]!.security_domain_id = invalid.workloads[1]!.security_domain.id;
  await page.getByLabel('Complete intent document').fill(JSON.stringify(invalid));
  await page.getByRole('button', { name: 'Create application', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('nic');
  await expect(page.getByLabel('Complete intent document')).toHaveValue(JSON.stringify(invalid));
  await expect(page.getByRole('alert')).toBeFocused();
  await page.getByLabel('Intent JSON file').setInputFiles({ name: 'permit-desk.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(fixture.intent)) });
  await page.getByRole('button', { name: 'Create application', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Browser Permit Desk', exact: true })).toBeVisible();
  await expect(page.getByRole('status')).toContainText('Published revision 1');
  await expect(page.getByText('security.unsupported_control', { exact: false }).first()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Dependency direction and readiness' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Data and recovery' })).toBeVisible();
  const applicationUrl = page.url();
  await page.getByRole('link', { name: 'Revise this intent' }).click();
  await expect(page).toHaveURL(/\/edit\?/);
  await expect(page.getByLabel('Virtual CPUs', { exact: true }).first()).toBeVisible();
  const editUrl = page.url();
  const stale = await context.newPage();
  stale.on('dialog', dialog => { void dialog.accept(); });
  await stale.goto(editUrl);
  const importedEdit: Intent = structuredClone(fixture.intent);
  importedEdit.workloads[0]!.compute.vcpus = 6;
  await stale.getByRole('button', { name: 'Import complete intent', exact: true }).click();
  await stale.getByLabel('Complete intent document').fill(JSON.stringify(importedEdit));
  await page.getByLabel('Virtual CPUs', { exact: true }).first().fill('4');
  await page.getByRole('button', { name: 'Publish new revision' }).click();
  await expect(page.getByRole('status')).toContainText('Published revision 2');
  await stale.getByRole('button', { name: 'Publish new revision' }).click();
  await expect(stale.getByRole('alert')).toContainText('changed');
  await expect(stale.getByLabel('Complete intent document')).toHaveValue(JSON.stringify(importedEdit));
  await stale.getByRole('button', { name: 'Review current version' }).click();
  await expect(stale.getByRole('status')).toContainText('current: 4; your draft: 6');
  await stale.getByRole('button', { name: 'Use reviewed current version as base' }).click();
  await stale.getByRole('button', { name: 'Publish new revision' }).click();
  await expect(stale.getByRole('status')).toContainText('Published revision 3');
  await stale.getByLabel('Compare with').selectOption({ label: 'Revision 1' });
  await stale.getByRole('link', { name: 'Compare revisions' }).click();
  await expect(stale.getByRole('heading', { name: 'Revision 1 to 3' })).toBeVisible();
  const row = stale.getByRole('row').filter({ has: stale.getByRole('rowheader', { name: 'workloads.0.compute.vcpus', exact: true }) });
  await expect(row).toContainText('2');
  await expect(row).toContainText('6');
  await stale.getByRole('link', { name: 'Revise this intent' }).click();
  await stale.getByLabel('Virtual CPUs', { exact: true }).first().fill('8');
  const applicationId = new URL(applicationUrl).pathname.split('/').at(-1)!;
  writeFileSync(fixture.fault_file, JSON.stringify({ path: `/v1/tenants/${fixture.tenant}/applications/${applicationId}/intent-revisions` }));
  await stale.getByRole('button', { name: 'Publish new revision' }).click();
  await expect(stale.getByRole('alert')).toContainText('not confirmed');
  await expect(stale.getByLabel('Virtual CPUs', { exact: true }).first()).toBeDisabled();
  await stale.getByRole('button', { name: 'Retry unchanged command' }).click();
  await expect(stale.getByRole('status')).toContainText('Published revision 4');
  await expect(stale.getByRole('link', { name: /^Revision [0-9]+$/ })).toHaveCount(4);
  await stale.getByRole('link', { name: 'Revision 1', exact: true }).click();
  await expect(stale.getByText('2 vCPUs', { exact: false }).first()).toBeVisible();
  await stale.setViewportSize({ width: 640, height: 800 });
  await stale.evaluate(() => { document.documentElement.style.zoom = '2'; });
  expect(await stale.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth+2)).toBe(true);
  await stale.keyboard.press('Tab');
  expect(await stale.evaluate(() => document.activeElement !== document.body)).toBe(true);
  await stale.getByRole('link', { name: 'Revise this intent' }).click();
  await stale.getByLabel('Virtual CPUs', { exact: true }).first().fill('10');
  const revoked = await request.post(`${fixture.governance_url}/v1/tenants/${fixture.tenant}/memberships`, { ignoreHTTPSErrors: true,
    headers: { Authorization: `Bearer ${fixture.console_workload}`, 'X-Console-Session': fixture.admin_token, 'Idempotency-Key': crypto.randomUUID() },
    data: { revision: fixture.membership.revision, subject: 'p03-author', role: 'author', state: 'revoked', site_id: null, environment: null, expires_at: null } });
  expect(revoked.status()).toBe(200);
  await stale.getByRole('button', { name: 'Publish new revision' }).click();
  await expect(stale).toHaveURL(/\/account$/);
  await expect(stale.getByLabel('Virtual CPUs', { exact: true })).toHaveCount(0);
  await stale.goBack();
  await expect(stale.getByLabel('Virtual CPUs', { exact: true })).toHaveCount(0);
  await page.goto(`/tenants/${fixture.foreign_tenant}/applications`);
  await expect(page).toHaveURL(/\/account$/);
  expect(errors).toEqual([]);
  await context.close();
});
